/**
 * Sample of 30 real DGT questions from the content JSON files.
 * This will be replaced by Supabase queries once the backend is wired up.
 */

export interface TestQuestion {
  id: string;
  number: number;
  enunciado: string;
  opciones: { key: string; texto: string }[];
  correcta: string;
  explicacion: string;
  pista?: string;
  tipoPregunta?: string;
  hasImage: boolean;
  imageSrc: string | null;
  tema: string;
}

export const sampleTestQuestions: TestQuestion[] = [
  // ── directa ──
  {
    id: "d-2",
    number: 1,
    enunciado: "\u00bfPuede realizar un cambio de sentido en un lugar donde est\u00e9 prohibido adelantar?",
    opciones: [
      { key: "A", texto: "S\u00ed, excepto entre la puesta y la salida de sol, porque disminuye la visibilidad." },
      { key: "B", texto: "No, salvo que el cambio de sentido est\u00e9 expresamente autorizado." },
      { key: "C", texto: "S\u00ed, cuando la circulaci\u00f3n en sentido contrario lo permita." },
    ],
    correcta: "B",
    explicacion: "Donde est\u00e1 prohibido adelantar tambi\u00e9n est\u00e1 prohibido cambiar de sentido, salvo autorizaci\u00f3n expresa.",
    pista: "Piensa en la relaci\u00f3n entre las prohibiciones de adelantar y cambiar de sentido.",
    hasImage: true,
    imageSrc: "https://www.todotest.com/tests/imgs/1052.jpg",
    tema: "Maniobras",
  },
  {
    id: "d-3",
    number: 2,
    enunciado: "En un veh\u00edculo de autoescuela realizando clases pr\u00e1cticas, \u00bfqui\u00e9n es considerado el conductor?",
    opciones: [
      { key: "A", texto: "Tanto al alumno como al profesor." },
      { key: "B", texto: "El alumno, ya que maneja el volante." },
      { key: "C", texto: "El profesor, por ser responsable de los mandos adicionales." },
    ],
    correcta: "C",
    explicacion: "El profesor es el conductor legal porque controla los mandos adicionales del veh\u00edculo.",
    pista: "Piensa en qui\u00e9n tiene el control real del veh\u00edculo.",
    hasImage: false,
    imageSrc: null,
    tema: "Normativa",
  },
  {
    id: "d-1",
    number: 3,
    enunciado: "Circulando con lluvia muy intensa, \u00bfes correcto encender la luz antiniebla trasera?",
    opciones: [
      { key: "A", texto: "S\u00ed." },
      { key: "B", texto: "No, s\u00f3lo puede utilizarse con niebla densa o fuerte nevada." },
      { key: "C", texto: "S\u00ed, pero su uso es opcional." },
    ],
    correcta: "A",
    explicacion: "La luz antiniebla trasera puede usarse con lluvia muy intensa, adem\u00e1s de con niebla densa y nieve.",
    pista: "La normativa contempla m\u00e1s situaciones que solo niebla para esta luz.",
    hasImage: false,
    imageSrc: null,
    tema: "Alumbrado",
  },
  {
    id: "d-19",
    number: 4,
    enunciado: "\u00bfPuede circular con su motocicleta por un carril bus?",
    opciones: [
      { key: "A", texto: "No, con car\u00e1cter general." },
      { key: "B", texto: "S\u00ed, pero s\u00f3lo para adelantar y durante el recorrido indispensable." },
      { key: "C", texto: "S\u00ed, en caso de circulaci\u00f3n muy densa." },
    ],
    correcta: "A",
    explicacion: "Con car\u00e1cter general, las motocicletas no pueden circular por un carril bus, salvo se\u00f1alizaci\u00f3n local que lo permita.",
    pista: "Piensa en para qu\u00e9 tipo de veh\u00edculos est\u00e1 reservado este carril.",
    hasImage: true,
    imageSrc: "https://www.todotest.com/tests/imgs/0249.jpg",
    tema: "Circulaci\u00f3n",
  },
  {
    id: "d-14",
    number: 5,
    enunciado: "El titular de permiso de conducci\u00f3n de clase B con una antig\u00fcedad mayor de 3 a\u00f1os, \u00bfpuede conducir una motocicleta de 125 cc.?",
    opciones: [
      { key: "A", texto: "No, porque es necesario obtener el permiso de la clase A1." },
      { key: "B", texto: "S\u00ed, el permiso de la clase \"B\" autoriza a conducir motocicletas de hasta 125 cc." },
      { key: "C", texto: "S\u00ed, pero s\u00f3lo por el territorio nacional." },
    ],
    correcta: "C",
    explicacion: "S\u00ed puede pero SOLO en Espa\u00f1a (territorio nacional), no en otros pa\u00edses de la UE, y requiere 3+ a\u00f1os de antig\u00fcedad.",
    pista: "F\u00edjate en las restricciones territoriales del permiso B para motos.",
    hasImage: true,
    imageSrc: "https://www.todotest.com/tests/imgs/0036.jpg",
    tema: "Permisos",
  },
  {
    id: "d-16",
    number: 6,
    enunciado: "En un estrechamiento sin se\u00f1ales de prioridad se encuentran un turismo que arrastra un remolque y un autob\u00fas, sin que se sepa cu\u00e1l entr\u00f3 primero, \u00bfqu\u00e9 veh\u00edculo tiene preferencia?",
    opciones: [
      { key: "A", texto: "El que tenga que dar marcha atr\u00e1s m\u00e1s distancia." },
      { key: "B", texto: "El autob\u00fas." },
      { key: "C", texto: "El turismo que arrastra el remolque." },
    ],
    correcta: "C",
    explicacion: "Tiene preferencia el veh\u00edculo que tendr\u00eda que dar marcha atr\u00e1s m\u00e1s distancia (el turismo con remolque).",
    pista: "Piensa en cu\u00e1l de los dos veh\u00edculos tendr\u00eda m\u00e1s dificultad para retroceder.",
    hasImage: false,
    imageSrc: null,
    tema: "Prioridad",
  },
  {
    id: "d-27",
    number: 7,
    enunciado: "\u00bfD\u00f3nde se colocar\u00e1 un ciclomotor para girar a la izquierda en una v\u00eda interurbana?",
    opciones: [
      { key: "A", texto: "En la parte central de su carril." },
      { key: "B", texto: "Si no existe carril espec\u00edfico para realizar el giro, se situar\u00e1 en la derecha, fuera de la calzada." },
      { key: "C", texto: "En el eje de la calzada si la v\u00eda es de doble sentido." },
    ],
    correcta: "B",
    explicacion: "Los ciclomotores se sit\u00faan a la derecha fuera de la calzada para girar a la izquierda, no en el centro como los coches.",
    pista: "Los ciclomotores no se colocan igual que los coches para girar.",
    hasImage: true,
    imageSrc: "https://www.todotest.com/tests/imgs/0080.jpg",
    tema: "Maniobras",
  },
  {
    id: "d-91",
    number: 8,
    enunciado: "Entre la puesta y la salida del sol, \u00bfest\u00e1 permitido conducir una motocicleta que arrastra un remolque?",
    opciones: [
      { key: "A", texto: "S\u00ed, si se hace a una velocidad un 10 por ciento por debajo de la gen\u00e9rica de la v\u00eda." },
      { key: "B", texto: "S\u00ed, como a cualquier otra hora del d\u00eda." },
      { key: "C", texto: "No." },
    ],
    correcta: "C",
    explicacion: "Las motocicletas con remolque no pueden circular de noche, bajo ninguna circunstancia.",
    pista: "Hay restricciones horarias espec\u00edficas para ciertos conjuntos de veh\u00edculos.",
    hasImage: false,
    imageSrc: null,
    tema: "Circulaci\u00f3n",
  },
  {
    id: "d-ciclistas",
    number: 9,
    enunciado: "Circula con su turismo por una v\u00eda que se cruza con un carril-bici; \u00bfdebe ceder el paso a los ciclistas?",
    opciones: [
      { key: "A", texto: "No. Los ciclistas no tienen prioridad de paso frente a los veh\u00edculos de motor." },
      { key: "B", texto: "S\u00ed, siempre." },
      { key: "C", texto: "S\u00f3lo cuando los ciclistas se aproximen por su derecha." },
    ],
    correcta: "B",
    explicacion: "Siempre se cede el paso a ciclistas en carril-bici se\u00f1alizado, independientemente de por d\u00f3nde se aproximen.",
    pista: "Un carril-bici se\u00f1alizado otorga derechos especiales a sus usuarios.",
    hasImage: true,
    imageSrc: "https://www.todotest.com/tests/imgs/r406.jpg",
    tema: "Prioridad",
  },
  {
    id: "d-13",
    number: 10,
    enunciado: "Una persona provista de un certificado m\u00e9dico que le exima de utilizar los sistemas de retenci\u00f3n del veh\u00edculo, \u00bfest\u00e1 exenta de llevar abrochado el cintur\u00f3n de seguridad?",
    opciones: [
      { key: "A", texto: "S\u00ed." },
      { key: "B", texto: "No." },
      { key: "C", texto: "\u00danicamente fuera de poblado." },
    ],
    correcta: "A",
    explicacion: "S\u00ed est\u00e1 exenta si tiene certificado m\u00e9dico oficial que la exima de utilizar los sistemas de retenci\u00f3n.",
    pista: "Existen excepciones m\u00e9dicas reconocidas por la ley.",
    hasImage: false,
    imageSrc: null,
    tema: "Seguridad",
  },
  // ── situacional ──
  {
    id: "s-368",
    number: 11,
    enunciado: "En una intersecci\u00f3n sin se\u00f1alizar, tienen prioridad de paso los veh\u00edculos que circulen por...",
    opciones: [
      { key: "A", texto: "una glorieta sobre los que pretenden entrar en ella." },
      { key: "B", texto: "un carril de uso exclusivo para determinados veh\u00edculos." },
      { key: "C", texto: "la v\u00eda sin pavimentar." },
    ],
    correcta: "A",
    explicacion: "Los veh\u00edculos dentro de una glorieta siempre tienen prioridad sobre los que pretenden entrar.",
    pista: "Recuerda la regla espec\u00edfica de las glorietas.",
    hasImage: true,
    imageSrc: "https://www.todotest.com/tests/imgs/1159.jpg",
    tema: "Prioridad",
  },
  {
    id: "s-316",
    number: 12,
    enunciado: "En un t\u00fanel, \u00bfqu\u00e9 distancia de seguridad se debe dejar con el veh\u00edculo que circula delante?",
    opciones: [
      { key: "A", texto: "100 metros, al menos, cuando no se pretenda adelantar." },
      { key: "B", texto: "\u00danicamente la distancia suficiente para no colisionar en caso de frenado brusco." },
      { key: "C", texto: "200 metros." },
    ],
    correcta: "A",
    explicacion: "En t\u00faneles se deben mantener al menos 100 metros de distancia con el veh\u00edculo precedente cuando no se pretende adelantar.",
    pista: "Los t\u00faneles tienen normas espec\u00edficas de distancia m\u00e1s estrictas.",
    hasImage: true,
    imageSrc: "https://www.todotest.com/tests/imgs/p31.jpg",
    tema: "Distancia de seguridad",
  },
  {
    id: "s-1587",
    number: 13,
    enunciado: "En caso de sufrir un revent\u00f3n circulando por una v\u00eda a velocidad elevada, \u00bfes aconsejable pisar el pedal de freno con brusquedad?",
    opciones: [
      { key: "A", texto: "S\u00ed, para mantener con mayor facilidad la trayector\u00eda del veh\u00edculo." },
      { key: "B", texto: "No, el frenado debe ser suave y progresivo." },
      { key: "C", texto: "Solo si el revent\u00f3n se produce en una de las ruedas delanteras." },
    ],
    correcta: "B",
    explicacion: "Frenar bruscamente con un revent\u00f3n empeora la situaci\u00f3n. El frenado debe ser suave y progresivo.",
    pista: "En situaciones de emergencia, las reacciones bruscas suelen empeorar las cosas.",
    hasImage: true,
    imageSrc: "https://www.todotest.com/tests/imgs/0582.jpg",
    tema: "Emergencias",
  },
  {
    id: "s-1792",
    number: 14,
    enunciado: "En una intersecci\u00f3n se\u00f1alizada en la que se encuentra un agente regulando el tr\u00e1fico, \u00bfqu\u00e9 debe hacer?",
    opciones: [
      { key: "A", texto: "Aplicar las normas generales de prioridad de paso de los veh\u00edculos que se acerquen por la derecha." },
      { key: "B", texto: "Obedecer las se\u00f1ales del agente." },
      { key: "C", texto: "Obedecer las se\u00f1ales de tr\u00e1fico que regulan la prioridad." },
    ],
    correcta: "B",
    explicacion: "Las indicaciones de los agentes prevalecen sobre cualquier otra se\u00f1alizaci\u00f3n.",
    pista: "Existe una jerarqu\u00eda clara entre los distintos tipos de se\u00f1alizaci\u00f3n.",
    hasImage: true,
    imageSrc: "https://www.todotest.com/tests/imgs/0644.jpg",
    tema: "Se\u00f1alizaci\u00f3n",
  },
  {
    id: "s-1668",
    number: 15,
    enunciado: "En v\u00edas urbanas, si no pretende adelantar, \u00bfqu\u00e9 distancia de seguridad se debe mantener con el turismo que circula delante?",
    opciones: [
      { key: "A", texto: "Aquella que permita que una motocicleta adelante con seguridad." },
      { key: "B", texto: "La que permita detenerse sin colisionar con el veh\u00edculo que va delante en caso de que frene bruscamente." },
      { key: "C", texto: "Siempre 50 metros." },
    ],
    correcta: "B",
    explicacion: "En v\u00edas urbanas, la distancia de seguridad es la que permita detenerse sin colisionar si el veh\u00edculo de delante frena bruscamente.",
    pista: "En v\u00edas urbanas la distancia se mide por capacidad de reacci\u00f3n, no por metros fijos.",
    hasImage: true,
    imageSrc: "https://www.todotest.com/tests/imgs/0351.jpg",
    tema: "Distancia de seguridad",
  },
  // ── completar ──
  {
    id: "c-227",
    number: 16,
    enunciado: "En las autov\u00edas, se permite circular...",
    opciones: [
      { key: "A", texto: "a peatones." },
      { key: "B", texto: "a veh\u00edculos de tracci\u00f3n animal." },
      { key: "C", texto: "por los arcenes, a conductores de bicicletas mayores de 14 a\u00f1os, salvo que se proh\u00edba por se\u00f1al." },
    ],
    correcta: "C",
    explicacion: "En autov\u00edas se permite circular por los arcenes a ciclistas mayores de 14 a\u00f1os, salvo prohibici\u00f3n por se\u00f1al.",
    pista: "No todos los usuarios tienen prohibido circular por autov\u00edas.",
    hasImage: true,
    imageSrc: "https://www.todotest.com/tests/imgs/0101.jpg",
    tema: "Circulaci\u00f3n",
  },
  {
    id: "c-235",
    number: 17,
    enunciado: "Si el resultado de las pruebas de alcoholemia es positivo el agente podr\u00e1 inmovilizar el veh\u00edculo, a no ser...",
    opciones: [
      { key: "A", texto: "que el conductor haga efectiva en el acto la sanci\u00f3n econ\u00f3mica impuesta." },
      { key: "B", texto: "que en el veh\u00edculo viajen ni\u00f1os o ancianos." },
      { key: "C", texto: "que pueda hacerse cargo de su conducci\u00f3n otra persona debidamente habilitada." },
    ],
    correcta: "C",
    explicacion: "Si otra persona debidamente habilitada puede hacerse cargo de la conducci\u00f3n, no se inmoviliza el veh\u00edculo.",
    pista: "Piensa en qu\u00e9 alternativa evitar\u00eda tener que inmovilizar el veh\u00edculo.",
    hasImage: false,
    imageSrc: null,
    tema: "Normativa",
  },
  {
    id: "c-346",
    number: 18,
    enunciado: "Los veh\u00edculos que circulen por el arc\u00e9n tienen prohibido circular en posici\u00f3n paralela, excepto...",
    opciones: [
      { key: "A", texto: "los que circulen muy despacio." },
      { key: "B", texto: "los ciclomotores y las motocicletas." },
      { key: "C", texto: "las bicicletas." },
    ],
    correcta: "C",
    explicacion: "Solo las bicicletas pueden circular en paralelo por el arc\u00e9n; ciclomotores y motocicletas no.",
    pista: "Solo un tipo de veh\u00edculo tiene esta excepci\u00f3n en el arc\u00e9n.",
    hasImage: true,
    imageSrc: "https://www.todotest.com/tests/imgs/0160.jpg",
    tema: "Circulaci\u00f3n",
  },
  {
    id: "c-540",
    number: 19,
    enunciado: "En los estrechamientos en tramos de gran pendiente, si no hay se\u00f1alizaci\u00f3n expresa al efecto, tendr\u00e1 la preferencia de paso el veh\u00edculo que circule en sentido...",
    opciones: [
      { key: "A", texto: "ascendente, salvo si pudiera llegar antes a un apartadero." },
      { key: "B", texto: "ascendente, en todo caso." },
      { key: "C", texto: "descendente, salvo si pudiera llegar antes a un apartadero." },
    ],
    correcta: "A",
    explicacion: "En pendientes, tiene preferencia el veh\u00edculo en sentido ascendente, salvo que pueda llegar antes a un apartadero.",
    pista: "El veh\u00edculo que sube tiene ventaja, pero hay una excepci\u00f3n pr\u00e1ctica.",
    hasImage: false,
    imageSrc: null,
    tema: "Prioridad",
  },
  {
    id: "c-1314",
    number: 20,
    enunciado: "Los animales pueden circular...",
    opciones: [
      { key: "A", texto: "\u00fanicamente por v\u00edas interurbanas." },
      { key: "B", texto: "por todas las v\u00edas, excepto por autopistas y autov\u00edas." },
      { key: "C", texto: "por todas las v\u00edas sin excepci\u00f3n." },
    ],
    correcta: "B",
    explicacion: "Los animales pueden circular por todas las v\u00edas excepto autopistas y autov\u00edas.",
    pista: "Hay dos tipos de v\u00edas de alta velocidad donde no se permite.",
    hasImage: false,
    imageSrc: null,
    tema: "Circulaci\u00f3n",
  },
  // ── dato ──
  {
    id: "dt-4",
    number: 21,
    enunciado: "\u00bfD\u00f3nde est\u00e1 permitido que viaje un ni\u00f1o que no alcance los 135 cent\u00edmetros de estatura?",
    opciones: [
      { key: "A", texto: "En cualquiera de los asientos traseros utilizando el cintur\u00f3n para adultos." },
      { key: "B", texto: "En un asiento delantero o trasero, utilizando siempre el cintur\u00f3n de seguridad para adultos." },
      { key: "C", texto: "En el asiento trasero, utilizando siempre un dispositivo de retenci\u00f3n homologado en funci\u00f3n de su talla y peso." },
    ],
    correcta: "C",
    explicacion: "Los ni\u00f1os que no alcancen los 135 cm deben viajar en asiento trasero con sistema de retenci\u00f3n homologado.",
    pista: "La ley exige un sistema espec\u00edfico adaptado al ni\u00f1o, no el cintur\u00f3n de adultos.",
    hasImage: true,
    imageSrc: "https://www.todotest.com/tests/imgs/0004.jpg",
    tema: "Seguridad",
  },
  {
    id: "dt-12",
    number: 22,
    enunciado: "\u00bfCu\u00e1l es la tasa de alcohol m\u00e1xima permitida a un conductor novel?",
    opciones: [
      { key: "A", texto: "0,25 miligramos de alcohol por litro de aire espirado." },
      { key: "B", texto: "0,3 miligramos de alcohol por litro de aire espirado." },
      { key: "C", texto: "0,15 miligramos de alcohol por litro de aire espirado." },
    ],
    correcta: "C",
    explicacion: "La tasa m\u00e1xima para conductores noveles es 0,15 mg/l en aire espirado (0,3 g/l en sangre).",
    pista: "Los conductores noveles tienen l\u00edmites m\u00e1s restrictivos que los generales.",
    hasImage: true,
    imageSrc: "https://www.todotest.com/tests/imgs/0096.jpg",
    tema: "Factores de riesgo",
  },
  {
    id: "dt-9",
    number: 23,
    enunciado: "\u00bfCu\u00e1ntos espejos retrovisores tienen que llevar instalados las motocicletas?",
    opciones: [
      { key: "A", texto: "Obligatoriamente uno en el lado derecho, pero pueden llevar dos." },
      { key: "B", texto: "Siempre deben llevar dos espejos, uno en cada lado." },
      { key: "C", texto: "Un espejo exterior izquierdo si no superan los 100 km/h y dos, uno en cada lado, si la velocidad es mayor." },
    ],
    correcta: "C",
    explicacion: "Las motocicletas necesitan un espejo izquierdo si no superan 100 km/h, y dos si superan esa velocidad.",
    pista: "El n\u00famero de espejos depende de la velocidad m\u00e1xima del veh\u00edculo.",
    hasImage: false,
    imageSrc: null,
    tema: "Equipamiento",
  },
  {
    id: "dt-43",
    number: 24,
    enunciado: "\u00bfCu\u00e1l es la velocidad m\u00e1xima gen\u00e9rica para un turismo en autov\u00eda?",
    opciones: [
      { key: "A", texto: "90 km/h." },
      { key: "B", texto: "100 km/h." },
      { key: "C", texto: "120 km/h." },
    ],
    correcta: "C",
    explicacion: "La velocidad m\u00e1xima gen\u00e9rica para un turismo en autov\u00eda es de 120 km/h.",
    pista: "Es la velocidad m\u00e1xima m\u00e1s alta permitida en Espa\u00f1a.",
    hasImage: true,
    imageSrc: "https://www.todotest.com/tests/imgs/0027.jpg",
    tema: "Velocidad",
  },
  {
    id: "dt-24",
    number: 25,
    enunciado: "En esta v\u00eda de poblado, \u00bfa qu\u00e9 velocidad como m\u00e1ximo podremos circular en ausencia de se\u00f1alizaci\u00f3n espec\u00edfica?",
    opciones: [
      { key: "A", texto: "A 30 km/h." },
      { key: "B", texto: "A 20 km/h." },
      { key: "C", texto: "A 50 km/h." },
    ],
    correcta: "A",
    explicacion: "En v\u00edas de poblado con plataforma \u00fanica (sin separaci\u00f3n calzada-acera), el l\u00edmite es 20 km/h; con un carril por sentido, 30 km/h.",
    pista: "Distingue entre v\u00edas de un carril por sentido y plataforma \u00fanica.",
    hasImage: false,
    imageSrc: null,
    tema: "Velocidad",
  },
  {
    id: "dt-30",
    number: 26,
    enunciado: "Fuera de poblado, \u00bfqu\u00e9 separaci\u00f3n lateral debe dejar una motocicleta al adelantar un cami\u00f3n?",
    opciones: [
      { key: "A", texto: "Una distancia proporcional a la velocidad a la que circule." },
      { key: "B", texto: "Un espacio no inferior a 1,50 metros." },
      { key: "C", texto: "Una separaci\u00f3n que considere segura en funci\u00f3n de las circunstancias del momento." },
    ],
    correcta: "B",
    explicacion: "Fuera de poblado, la separaci\u00f3n lateral m\u00ednima al adelantar es de 1,50 metros.",
    pista: "Fuera de poblado existe una distancia m\u00ednima fija obligatoria.",
    hasImage: false,
    imageSrc: null,
    tema: "Maniobras",
  },
  {
    id: "dt-15",
    number: 27,
    enunciado: "\u00bfEst\u00e1 permitido colocar la se\u00f1al luminosa de prese\u00f1alizaci\u00f3n de peligro, V-16, alejada del veh\u00edculo averiado?",
    opciones: [
      { key: "A", texto: "S\u00ed, alejado se podr\u00e1 apreciar mejor." },
      { key: "B", texto: "S\u00ed, debe estar al menos a 100 metros." },
      { key: "C", texto: "No, se debe colocar en la parte m\u00e1s alta posible del veh\u00edculo inmovilizado." },
    ],
    correcta: "C",
    explicacion: "La se\u00f1al V-16 se coloca en la parte m\u00e1s alta del veh\u00edculo inmovilizado, no alejada de \u00e9l.",
    pista: "La V-16 se coloca sobre el veh\u00edculo, no en la v\u00eda.",
    hasImage: true,
    imageSrc: "https://www.todotest.com/tests/imgs/s1.jpg",
    tema: "Emergencias",
  },
  {
    id: "dt-40",
    number: 28,
    enunciado: "\u00bfEst\u00e1 correctamente inmovilizada esta furgoneta?",
    opciones: [
      { key: "A", texto: "S\u00ed, ya que est\u00e1 correctamente se\u00f1alizada y no obstaculiza el paso." },
      { key: "B", texto: "S\u00ed, siempre que se trate de una parada." },
      { key: "C", texto: "No, ya que entre la furgoneta y la marca continua hay una distancia inferior a 3 metros." },
    ],
    correcta: "C",
    explicacion: "No est\u00e1 correctamente inmovilizada porque debe haber al menos 3 metros entre el veh\u00edculo y la l\u00ednea continua.",
    pista: "F\u00edjate en la distancia m\u00ednima requerida respecto a las marcas viales.",
    hasImage: false,
    imageSrc: null,
    tema: "Estacionamiento",
  },
  {
    id: "dt-5",
    number: 29,
    enunciado: "Con esta se\u00f1alizaci\u00f3n, \u00bfa qu\u00e9 velocidad debe circular?",
    opciones: [
      { key: "A", texto: "Obligatoriamente a 30 km/h." },
      { key: "B", texto: "Al menos a 30 km/h." },
      { key: "C", texto: "A 30 km/h, como recomendaci\u00f3n, durante el tramo que subsista el peligro." },
    ],
    correcta: "C",
    explicacion: "Se trata de una se\u00f1al de velocidad recomendada, no obligatoria ni m\u00ednima.",
    pista: "Distingue entre se\u00f1ales obligatorias, m\u00ednimas y recomendadas.",
    hasImage: true,
    imageSrc: "https://www.todotest.com/tests/imgs/0016.jpg",
    tema: "Se\u00f1alizaci\u00f3n",
  },
  {
    id: "c-450",
    number: 30,
    enunciado: "Modificar la se\u00f1alizaci\u00f3n de la v\u00eda...",
    opciones: [
      { key: "A", texto: "est\u00e1 prohibido, salvo por causa justificada." },
      { key: "B", texto: "no est\u00e1 prohibido, pero no es recomendable." },
      { key: "C", texto: "est\u00e1 permitido siempre que la modificaci\u00f3n ayude a aclarar el sentido de la se\u00f1alizaci\u00f3n." },
    ],
    correcta: "A",
    explicacion: "Modificar la se\u00f1alizaci\u00f3n de la v\u00eda est\u00e1 prohibido, salvo causa justificada.",
    pista: "Alterar elementos de la v\u00eda p\u00fablica tiene consecuencias legales.",
    hasImage: false,
    imageSrc: null,
    tema: "Normativa",
  },
];
