import type { TestQuestion } from "./mock-test-data";

/**
 * Validated DGT questions from the content pipeline.
 * Auto-generated by scripts/generate-question-bank.mjs — do not edit manually.
 */

export interface BankQuestion extends TestQuestion {
  temaId: string;
}

export const questionBank: BankQuestion[] = [
  {
    "id": "pregunta_B019",
    "number": 0,
    "enunciado": "Tiene el permiso B desde hace 4 años y quiere conducir una motocicleta de 125 cc y 11 kW de potencia. ¿Puede hacerlo?",
    "opciones": [
      {
        "key": "A",
        "texto": "Sí, siempre que cumpla con la formación obligatoria exigida"
      },
      {
        "key": "B",
        "texto": "Sí, sin ningún requisito adicional al tener más de 3 años de permiso B"
      },
      {
        "key": "C",
        "texto": "No, en ningún caso el permiso B permite conducir motocicletas"
      }
    ],
    "correcta": "A",
    "explicacion": "El permiso B permite conducir motocicletas de hasta 125 cc con un máximo de 11 kW de potencia, siempre que se tengan al menos 3 años de antigüedad del permiso B. Además, desde 2025, quienes cumplan los 3 años deben realizar un curso de formación obligatorio.\n\n- Opciones incorrectas: la segunda omite el requisito del curso de formación obligatorio; la tercera es falsa porque el permiso B sí autoriza a conducir motos de hasta 125 cc bajo ciertas condiciones\n- Conexión: esta autorización es válida solo en España y no tiene validez en otros países de la Unión Europea\n- Dato clave: máximo 125 cc, máximo 11 kW, mínimo 3 años de permiso B, relación potencia/peso máxima de 0,1 kW/kg",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_01",
    "tema": "El Conductor y el Permiso",
    "pista": "La normativa ha ido evolucionando en cuanto a los requisitos para esta autorización.",
    "tipoPregunta": "situacional"
  },
  {
    "id": "pregunta_B020",
    "number": 0,
    "enunciado": "¿Es válido mostrar el permiso de conducir a través de la aplicación miDGT en un control policial?",
    "opciones": [
      {
        "key": "A",
        "texto": "Sí, el permiso digital en miDGT tiene la misma validez legal que el físico"
      },
      {
        "key": "B",
        "texto": "No, es obligatorio llevar siempre el permiso en formato físico"
      },
      {
        "key": "C",
        "texto": "Solamente si además lleva una copia del permiso físico"
      }
    ],
    "correcta": "A",
    "explicacion": "Desde 2024, la aplicación miDGT permite mostrar el permiso de conducir digital con la misma validez legal que el documento físico. No es necesario llevar ambos formatos.\n\n- Opciones incorrectas: la segunda desconoce la validez del permiso digital; la tercera exige una copia adicional que no es necesaria según la normativa vigente\n- Conexión: la app miDGT también permite consultar el estado del tráfico, datos del vehículo y notificaciones de la DGT\n- Error común: desconfiar de la validez del formato digital a pesar de que la normativa lo reconoce expresamente",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_01",
    "tema": "El Conductor y el Permiso",
    "pista": "La digitalización ha llegado también a los documentos del conductor.",
    "tipoPregunta": "directa"
  },
  {
    "id": "pregunta_B021",
    "number": 0,
    "enunciado": "Un conductor novel comienza con un saldo de 8 puntos. Si durante los 2 primeros años no comete infracciones graves ni muy graves, ¿cuántos puntos tendrá?",
    "opciones": [
      {
        "key": "A",
        "texto": "12 puntos"
      },
      {
        "key": "B",
        "texto": "15 puntos"
      },
      {
        "key": "C",
        "texto": "8 puntos, los mantiene hasta hacer un curso"
      }
    ],
    "correcta": "A",
    "explicacion": "Los conductores noveles empiezan con 8 puntos. Si durante los 2 primeros años no cometen infracciones graves ni muy graves, su saldo sube automáticamente a 12 puntos, que es el saldo estándar.\n\n- Opciones incorrectas: 15 puntos es el máximo acumulable mediante bonificaciones y cursos, pero no se alcanza directamente tras 2 años; los 8 puntos no se mantienen si no hay infracciones, sino que suben automáticamente a 12\n- Conexión: para llegar a los 15 puntos máximos se necesitan años adicionales sin infracciones y la posibilidad de realizar cursos de conducción segura y eficiente\n- Dato clave: novel = 8 puntos; tras 2 años sin infracciones graves = 12 puntos; máximo acumulable = 15 puntos",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_01",
    "tema": "El Conductor y el Permiso",
    "pista": "El sistema de puntos recompensa la conducción sin infracciones.",
    "tipoPregunta": "dato"
  },
  {
    "id": "pregunta_B001",
    "number": 0,
    "enunciado": "Los neumáticos de su turismo presentan una profundidad de dibujo de 1,4 mm. ¿Puede circular con ellos?",
    "opciones": [
      {
        "key": "A",
        "texto": "No, porque la profundidad mínima legal es 1,6 mm"
      },
      {
        "key": "B",
        "texto": "Sí, siempre que no llueva"
      },
      {
        "key": "C",
        "texto": "Sí, porque el mínimo legal es 1,0 mm"
      }
    ],
    "correcta": "A",
    "explicacion": "La profundidad mínima legal del dibujo de los neumáticos es de 1,6 mm. Con 1,4 mm se está por debajo del límite legal y no se puede circular.\n\n- Opciones incorrectas: la segunda opción sugiere que el clima condiciona la legalidad, lo cual es falso; la tercera indica un mínimo incorrecto de 1,0 mm\n- Conexión: aunque el mínimo legal es 1,6 mm, se recomienda cambiar los neumáticos cuando el dibujo baje de 3 mm, especialmente para prevenir el aquaplaning\n- Dato clave: profundidad mínima legal = 1,6 mm; recomendada para cambio = 3 mm",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_02",
    "tema": "El Vehículo",
    "pista": "Piensa en las cifras que aparecen en la normativa sobre el estado de los neumáticos.",
    "tipoPregunta": "directa"
  },
  {
    "id": "pregunta_B002",
    "number": 0,
    "enunciado": "Si el resultado de la ITV de su turismo es desfavorable...",
    "opciones": [
      {
        "key": "A",
        "texto": "puede circular durante un plazo máximo de 2 meses para reparar y volver a pasar la ITV"
      },
      {
        "key": "B",
        "texto": "no puede circular en ningún caso y debe trasladar el vehículo en grúa"
      },
      {
        "key": "C",
        "texto": "puede circular sin limitación de plazo hasta la próxima ITV programada"
      }
    ],
    "correcta": "A",
    "explicacion": "Con resultado desfavorable, el vehículo puede circular hasta 2 meses para realizar las reparaciones necesarias y volver a pasar la inspección. El resultado negativo es el que impide circular.\n\n- Opciones incorrectas: la segunda confunde desfavorable con negativo, que sí impide circular; la tercera ignora que existe un plazo máximo para subsanar los defectos\n- Conexión: si el resultado es negativo, el vehículo no puede circular y debe ser trasladado en grúa o reparado in situ\n- Error común: confundir los resultados desfavorable y negativo; desfavorable permite circular temporalmente, negativo no",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_02",
    "tema": "El Vehículo",
    "pista": "Hay una diferencia importante entre resultado desfavorable y resultado negativo.",
    "tipoPregunta": "completar"
  },
  {
    "id": "pregunta_B003",
    "number": 0,
    "enunciado": "Un turismo sin seguro obligatorio está aparcado en la vía pública, sin circular. ¿Puede ser sancionado su propietario?",
    "opciones": [
      {
        "key": "A",
        "texto": "Sí, todo vehículo a motor en la vía pública debe tener seguro, aunque esté aparcado"
      },
      {
        "key": "B",
        "texto": "No, porque el seguro solo es obligatorio cuando el vehículo circula"
      },
      {
        "key": "C",
        "texto": "No, en ningún caso se sanciona a un vehículo que no está circulando"
      }
    ],
    "correcta": "A",
    "explicacion": "Todo vehículo a motor que ocupe la vía pública debe tener seguro obligatorio en vigor, incluso si está aparcado y no circula. Solo se puede prescindir del seguro si el vehículo está dado de baja temporal o definitiva en la DGT.\n\n- Opciones incorrectas: ambas asumen erróneamente que el seguro solo es necesario para circular, cuando la obligación existe por el mero hecho de ocupar la vía pública\n- Conexión: la multa por vehículo sin seguro aparcado es de 800 euros; si está circulando puede ser de hasta 1.500 euros con posible inmovilización\n- Error común: muchos conductores creen que si no usan el coche no necesitan seguro; el Consorcio de Compensación de Seguros se encargará de reclamar los daños al propietario",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_02",
    "tema": "El Vehículo",
    "pista": "Recuerda que la obligación de asegurar no depende de si el vehículo se usa o no.",
    "tipoPregunta": "directa"
  },
  {
    "id": "pregunta_B004",
    "number": 0,
    "enunciado": "Conduce un vehículo eléctrico puro por una zona con muchos peatones. ¿Qué precaución especial debe tener en cuenta?",
    "opciones": [
      {
        "key": "A",
        "texto": "Que los peatones pueden no oírle debido al bajo nivel de ruido del vehículo"
      },
      {
        "key": "B",
        "texto": "Ninguna especial, ya que todos los eléctricos emiten sonido artificial a cualquier velocidad"
      },
      {
        "key": "C",
        "texto": "Que debe usar el claxon en todo momento para alertar a los peatones"
      }
    ],
    "correcta": "A",
    "explicacion": "Los vehículos eléctricos producen muy poco ruido, lo que supone un riesgo para peatones, ciclistas y niños que pueden no advertir su presencia. El sistema AVAS emite sonido artificial, pero solo a velocidades inferiores a 20 km/h.\n\n- Opciones incorrectas: la segunda afirma que el sonido se emite a cualquier velocidad, cuando el AVAS solo funciona por debajo de 20 km/h; la tercera propone usar el claxon constantemente, lo cual está prohibido como uso injustificado\n- Conexión: el peso elevado de las baterías también aumenta la distancia de frenado de los vehículos eléctricos\n- Dato clave: el sistema AVAS es obligatorio y emite sonido artificial a velocidades inferiores a 20 km/h",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_02",
    "tema": "El Vehículo",
    "pista": "Los vehículos eléctricos tienen una característica que afecta a cómo los perciben otros usuarios de la vía.",
    "tipoPregunta": "directa"
  },
  {
    "id": "pregunta_B005",
    "number": 0,
    "enunciado": "Si comprueba la presión de los neumáticos y resulta estar por debajo de lo recomendado por el fabricante, el efecto más probable es...",
    "opciones": [
      {
        "key": "A",
        "texto": "un mayor consumo de combustible y desgaste en los bordes del neumático"
      },
      {
        "key": "B",
        "texto": "un menor consumo de combustible y mayor agarre"
      },
      {
        "key": "C",
        "texto": "solamente un viaje más incómodo, sin otras consecuencias"
      }
    ],
    "correcta": "A",
    "explicacion": "La presión baja en los neumáticos provoca mayor consumo de combustible, desgaste irregular en los bordes, peor manejo y riesgo de reventón. Es una de las preguntas más frecuentes del examen.\n\n- Opciones incorrectas: la segunda describe el efecto contrario, ya que la presión baja aumenta el consumo; la tercera minimiza las consecuencias cuando en realidad hay riesgo de reventón\n- Conexión: la presión debe comprobarse con el neumático frío, ya que en caliente da lecturas superiores a las reales\n- Error común: confundir los efectos de presión alta y baja; presión alta desgasta el centro del neumático, presión baja desgasta los bordes",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_02",
    "tema": "El Vehículo",
    "pista": "La superficie de contacto del neumático con el suelo cambia según la presión.",
    "tipoPregunta": "completar"
  },
  {
    "id": "pregunta_B006",
    "number": 0,
    "enunciado": "Transporta en su turismo una carga divisible que sobresale por la parte trasera. ¿Cuánto puede sobresalir como máximo?",
    "opciones": [
      {
        "key": "A",
        "texto": "Hasta un 10% de la longitud del vehículo"
      },
      {
        "key": "B",
        "texto": "Hasta un 15% de la longitud del vehículo"
      },
      {
        "key": "C",
        "texto": "Nunca puede sobresalir la carga por detrás de un turismo"
      }
    ],
    "correcta": "A",
    "explicacion": "En turismos, la carga divisible puede sobresalir por detrás hasta un 10% de la longitud del vehículo. Si la carga fuera indivisible, el límite sería del 15%.\n\n- Opciones incorrectas: el 15% corresponde a carga indivisible, no divisible; la tercera es falsa porque sí se permite que la carga sobresalga por detrás con limitaciones\n- Conexión: la carga que sobresale por detrás debe señalizarse con un panel rojo y blanco (V-20) de día, y con luz roja más catadióptrico de noche\n- Dato clave: carga divisible = 10%, carga indivisible = 15%; por delante nunca puede sobresalir en turismos",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_03",
    "tema": "Carga, Pasajeros y Remolques",
    "pista": "Distingue entre carga divisible e indivisible para recordar el porcentaje correcto.",
    "tipoPregunta": "directa"
  },
  {
    "id": "pregunta_B007",
    "number": 0,
    "enunciado": "Viaja en su turismo con un niño de 4 años y 100 cm de altura. ¿Cómo debe viajar el menor?",
    "opciones": [
      {
        "key": "A",
        "texto": "En un sistema de retención infantil homologado, preferiblemente en el asiento trasero"
      },
      {
        "key": "B",
        "texto": "Con el cinturón de seguridad normal, siempre que vaya en el asiento trasero"
      },
      {
        "key": "C",
        "texto": "Sin ningún sistema especial si el asiento delantero tiene airbag activo"
      }
    ],
    "correcta": "A",
    "explicacion": "Los menores de 135 cm de altura deben utilizar obligatoriamente un sistema de retención infantil (SRI) homologado, y preferiblemente ir en los asientos traseros. El asiento central trasero es el más seguro.\n\n- Opciones incorrectas: la segunda permite usar solo el cinturón normal, lo cual es ilegal para menores de 135 cm; la tercera es peligrosa porque un SRI en sentido contrario a la marcha con airbag frontal activo puede causar lesiones graves\n- Conexión: la responsabilidad de que los menores lleven el SRI recae sobre el conductor, no sobre el menor; la sanción es de 200 euros y 4 puntos\n- Dato clave: SRI obligatorio hasta 135 cm de altura; recomendado hasta 150 cm",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_03",
    "tema": "Carga, Pasajeros y Remolques",
    "pista": "La obligatoriedad del SRI depende de la estatura del menor.",
    "tipoPregunta": "situacional"
  },
  {
    "id": "pregunta_B008",
    "number": 0,
    "enunciado": "Circula con su turismo y un remolque ligero por una autopista. ¿A qué velocidad máxima puede circular?",
    "opciones": [
      {
        "key": "A",
        "texto": "A 90 km/h"
      },
      {
        "key": "B",
        "texto": "A 120 km/h, igual que sin remolque"
      },
      {
        "key": "C",
        "texto": "A 80 km/h"
      }
    ],
    "correcta": "A",
    "explicacion": "Un turismo con remolque ligero (MMA igual o inferior a 750 kg) puede circular a un máximo de 90 km/h en autopista o autovía, y a 80 km/h en carretera convencional.\n\n- Opciones incorrectas: 120 km/h es la velocidad máxima de un turismo sin remolque; 80 km/h es la velocidad máxima con remolque pesado en autopista, no con el ligero\n- Conexión: un remolque pesado (MMA superior a 750 kg) tiene 10 km/h menos que el ligero en cada tipo de vía: 80 km/h en autopista y 70 km/h en convencional\n- Error común: confundir las velocidades del remolque ligero con las del pesado; la regla es que el pesado va siempre 10 km/h más lento",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_03",
    "tema": "Carga, Pasajeros y Remolques",
    "pista": "La velocidad con remolque siempre es inferior a la del turismo solo, y varía según el peso del remolque.",
    "tipoPregunta": "dato"
  },
  {
    "id": "pregunta_B009",
    "number": 0,
    "enunciado": "Circula por una vía urbana de un solo carril por sentido. ¿Cuál es la velocidad máxima permitida para su turismo?",
    "opciones": [
      {
        "key": "A",
        "texto": "30 km/h"
      },
      {
        "key": "B",
        "texto": "50 km/h"
      },
      {
        "key": "C",
        "texto": "40 km/h"
      }
    ],
    "correcta": "A",
    "explicacion": "En vías urbanas de un solo carril por sentido, la velocidad máxima es de 30 km/h. Si la vía tiene dos o más carriles por sentido, el límite sube a 50 km/h.\n\n- Opciones incorrectas: 50 km/h corresponde a vías urbanas de dos o más carriles por sentido, no de uno; 40 km/h no corresponde a ningún límite genérico establecido\n- Conexión: esta regla se introdujo para mejorar la seguridad de peatones y ciclistas en calles estrechas, reduciendo la gravedad de los atropellos\n- Dato clave: 1 carril por sentido = 30 km/h; 2 o más carriles por sentido = 50 km/h",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_04",
    "tema": "La Vía y sus Usuarios",
    "pista": "En las vías urbanas, el número de carriles por sentido determina el límite de velocidad.",
    "tipoPregunta": "dato"
  },
  {
    "id": "pregunta_B010",
    "number": 0,
    "enunciado": "Circula por una carretera convencional y necesita adelantar a un ciclista. La vía tiene línea continua. ¿Puede cruzarla para mantener la distancia lateral de seguridad?",
    "opciones": [
      {
        "key": "A",
        "texto": "Sí, está permitido cruzar la línea continua para garantizar los 1,5 metros de separación"
      },
      {
        "key": "B",
        "texto": "No, en ningún caso se puede cruzar la línea continua"
      },
      {
        "key": "C",
        "texto": "Sí, pero solamente si circula a menos de 50 km/h"
      }
    ],
    "correcta": "A",
    "explicacion": "Para adelantar a ciclistas se debe mantener una distancia lateral mínima de 1,5 metros. Está permitido invadir el carril contrario cruzando la línea continua si es necesario para garantizar esa distancia, siempre que se pueda hacer con seguridad.\n\n- Opciones incorrectas: la segunda es un absoluto incorrecto porque la norma contempla esta excepción para proteger a los ciclistas; la tercera añade una condición de velocidad que no existe en la normativa\n- Conexión: además de los 1,5 metros de distancia lateral, al adelantar ciclistas se debe reducir la velocidad 20 km/h por debajo del límite de la vía\n- Dato clave: distancia lateral mínima al adelantar ciclistas = 1,5 metros en cualquier tipo de vía",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_04",
    "tema": "La Vía y sus Usuarios",
    "pista": "La protección de los usuarios vulnerables puede justificar excepciones a ciertas normas de circulación.",
    "tipoPregunta": "situacional"
  },
  {
    "id": "pregunta_B011",
    "number": 0,
    "enunciado": "En una carretera 2+1, cuando usted circula por el tramo que tiene un solo carril en su sentido...",
    "opciones": [
      {
        "key": "A",
        "texto": "está prohibido adelantar y debe esperar al siguiente tramo de dos carriles"
      },
      {
        "key": "B",
        "texto": "puede adelantar si no hay tráfico en el carril contrario"
      },
      {
        "key": "C",
        "texto": "puede adelantar siempre que señalice con el intermitente"
      }
    ],
    "correcta": "A",
    "explicacion": "Las carreteras 2+1 alternan tramos de dos carriles con tramos de un carril por sentido. En el tramo de un solo carril, está prohibido adelantar porque el carril extra está asignado al sentido contrario.\n\n- Opciones incorrectas: la segunda ignora que en el tramo de un carril no hay carril disponible para adelantar de forma legal; la tercera sugiere que señalizar basta para poder adelantar, lo cual no es correcto\n- Conexión: estas carreteras se diseñan para reducir los accidentes frontales, que son la principal causa de muerte en carreteras convencionales\n- Excepción: cuando se circula por el tramo de dos carriles en su sentido, sí se puede adelantar utilizando el carril izquierdo",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_04",
    "tema": "La Vía y sus Usuarios",
    "pista": "En estas carreteras, los tramos de adelantamiento están claramente definidos.",
    "tipoPregunta": "completar"
  },
  {
    "id": "pregunta_B012",
    "number": 0,
    "enunciado": "Antes de cambiar de carril, ¿es suficiente comprobar los espejos retrovisores para asegurarse de que no viene otro vehículo?",
    "opciones": [
      {
        "key": "A",
        "texto": "No, además debe girar brevemente la cabeza para comprobar el ángulo muerto"
      },
      {
        "key": "B",
        "texto": "Sí, los espejos retrovisores cubren todas las zonas alrededor del vehículo"
      },
      {
        "key": "C",
        "texto": "Sí, siempre que los espejos estén correctamente regulados"
      }
    ],
    "correcta": "A",
    "explicacion": "Los espejos retrovisores no cubren los ángulos muertos del vehículo, que son zonas no visibles ni directamente ni por los espejos. Antes de cambiar de carril, incorporarse o adelantar, es obligatorio girar brevemente la cabeza para comprobar esas zonas.\n\n- Opciones incorrectas: la segunda y la tercera afirman que los espejos son suficientes, cuando todo vehículo tiene ángulos muertos que los espejos no cubren\n- Conexión: la técnica del giro holandés también utiliza el principio de girar el cuerpo al abrir la puerta del coche, evitando golpear a ciclistas o motoristas\n- Error común: confiar exclusivamente en los espejos y en el detector de ángulo muerto (BSM), que es solo una ayuda que no sustituye al giro de cabeza",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_04",
    "tema": "La Vía y sus Usuarios",
    "pista": "Todo vehículo tiene zonas que ningún espejo puede cubrir.",
    "tipoPregunta": "directa"
  },
  {
    "id": "pregunta_A020",
    "number": 0,
    "enunciado": "En España, como norma general, los vehículos deben circular...",
    "opciones": [
      {
        "key": "A",
        "texto": "por cualquier carril indistintamente siempre que no excedan el límite de velocidad"
      },
      {
        "key": "B",
        "texto": "por el carril central exclusivamente, salvo para adelantar o ser adelantados"
      },
      {
        "key": "C",
        "texto": "por el carril más a la derecha disponible, utilizando los izquierdos para adelantar"
      }
    ],
    "correcta": "C",
    "explicacion": "La norma general en España establece que se debe circular por el carril más a la derecha, reservando los carriles izquierdos para adelantar. Esto facilita el flujo de tráfico y permite los adelantamientos.\n\n- Opciones incorrectas: no se puede circular por cualquier carril indistintamente en vías interurbanas; no existe una regla de circular por el carril central, eso puede constituir infracción por no circular por la derecha\n- Conexión: en vías urbanas con más de un carril por sentido y tráfico denso, sí se permite utilizar el carril que mejor convenga al destino\n- Excepción: en poblado con 3 o más carriles por sentido se puede usar cualquiera",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_05",
    "tema": "Circulación y Velocidad",
    "pista": "La regla básica de circulación se basa en el sentido de marcha del país.",
    "tipoPregunta": "completar"
  },
  {
    "id": "pregunta_A021",
    "number": 0,
    "enunciado": "¿Está permitido utilizar el teléfono móvil sujetándolo con la mano mientras espera detenido en un semáforo en rojo?",
    "opciones": [
      {
        "key": "A",
        "texto": "Sí, porque al estar detenido no se está circulando y no hay ningún riesgo en ningún caso"
      },
      {
        "key": "B",
        "texto": "No, está prohibido manipular el móvil sujetándolo con la mano incluso con el vehículo detenido en un semáforo"
      },
      {
        "key": "C",
        "texto": "Sí, solamente si la conversación dura menos de un minuto"
      }
    ],
    "correcta": "B",
    "explicacion": "Está prohibido manipular el teléfono móvil sujetándolo con la mano en cualquier momento durante la conducción, incluidas las detenciones en semáforos y retenciones. Se considera infracción muy grave.\n\n- Opciones incorrectas: estar detenido en un semáforo no exime de la prohibición, ya que se sigue participando en el tráfico; no existe ninguna excepción por duración de la conversación\n- Conexión: la sanción por usar el móvil sujetándolo con la mano es de 200 euros y 6 puntos\n- Error común: muchos conductores creen que al estar parados en un semáforo pueden usar el móvil con la mano",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_05",
    "tema": "Circulación y Velocidad",
    "pista": "La prohibición se aplica mientras participas en el tráfico, no solo mientras te mueves.",
    "tipoPregunta": "directa"
  },
  {
    "id": "pregunta_A022",
    "number": 0,
    "enunciado": "Circula por una autopista con su turismo. ¿Cuál es la velocidad mínima a la que debe circular para no entorpecer la marcha normal del tráfico?",
    "opciones": [
      {
        "key": "A",
        "texto": "60 km/h, salvo circunstancias excepcionales como pendientes o congestión"
      },
      {
        "key": "B",
        "texto": "80 km/h obligatoriamente en todos los casos"
      },
      {
        "key": "C",
        "texto": "No existe velocidad mínima en ningún tipo de vía"
      }
    ],
    "correcta": "A",
    "explicacion": "La velocidad mínima en autopistas y autovías es de 60 km/h, que corresponde a la mitad de la velocidad máxima general de 120 km/h. Circular por debajo de esa velocidad sin causa justificada supone una infracción por entorpecer la circulación.\n\n- Opciones incorrectas: 80 km/h no es la velocidad mínima de autopistas; sí existe velocidad mínima en vías de alta capacidad\n- Conexión: los vehículos que no pueden alcanzar los 60 km/h (ciclomotores, vehículos especiales, bicicletas) tienen prohibida la circulación por autopistas y autovías\n- Dato clave: velocidad mínima en autopista/autovía = 60 km/h (mitad de 120 km/h)",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_05",
    "tema": "Circulación y Velocidad",
    "pista": "La velocidad mínima tiene una relación directa con la máxima de esa vía.",
    "tipoPregunta": "dato"
  },
  {
    "id": "pregunta_A023",
    "number": 0,
    "enunciado": "Circula con su turismo arrastrando un remolque ligero (MMA de 700 kg) por una autopista. ¿Cuál es la velocidad máxima a la que puede circular?",
    "opciones": [
      {
        "key": "A",
        "texto": "A 120 km/h, porque el remolque es ligero y nunca afecta a la velocidad máxima"
      },
      {
        "key": "B",
        "texto": "A 90 km/h, que es el límite para turismos con remolque ligero en autopista"
      },
      {
        "key": "C",
        "texto": "A 80 km/h en cualquier caso, independientemente del peso del remolque"
      }
    ],
    "correcta": "B",
    "explicacion": "Un turismo con remolque ligero (MMA igual o inferior a 750 kg) tiene una velocidad máxima de 90 km/h en autopista y autovía, es decir, 30 km/h menos que un turismo sin remolque.\n\n- Opciones incorrectas: el remolque ligero sí reduce la velocidad máxima, de 120 a 90 km/h; 80 km/h es el límite para remolques pesados (MMA superior a 750 kg) en autopista, no para los ligeros\n- Conexión: el remolque pesado (MMA superior a 750 kg) tiene un límite aún menor de 80 km/h en autopista, 10 km/h menos que el ligero\n- Dato clave: turismo + remolque ligero en autopista = 90 km/h; turismo + remolque pesado en autopista = 80 km/h",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_05",
    "tema": "Circulación y Velocidad",
    "pista": "El peso del remolque determina cuánto se reduce la velocidad máxima.",
    "tipoPregunta": "situacional"
  },
  {
    "id": "pregunta_A024",
    "number": 0,
    "enunciado": "La distancia de detención de un vehículo es igual a...",
    "opciones": [
      {
        "key": "A",
        "texto": "solamente la distancia de frenado, ya que la reacción no influye nunca en la detención"
      },
      {
        "key": "B",
        "texto": "exclusivamente la distancia de reacción, que es la única que determina cuándo se detiene el vehículo"
      },
      {
        "key": "C",
        "texto": "la distancia de reacción más la distancia de frenado"
      }
    ],
    "correcta": "C",
    "explicacion": "La distancia de detención es la suma de la distancia de reacción (lo que se recorre mientras el conductor reacciona antes de pisar el freno) y la distancia de frenado (lo que se recorre frenando hasta detenerse completamente).\n\n- Opciones incorrectas: la distancia de reacción es fundamental y no puede ignorarse, ya que durante ese tiempo el vehículo sigue avanzando a la misma velocidad; la distancia de reacción sola no incluye lo que se recorre frenando\n- Conexión: a 120 km/h, la distancia de detención total es de aproximadamente 105 metros en asfalto seco (33 metros de reacción + 72 metros de frenado)\n- Dato clave: el tiempo de reacción normal es de 0,75 a 1 segundo, pero con fatiga puede llegar a 2 segundos y con alcohol puede duplicarse o triplicarse",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_05",
    "tema": "Circulación y Velocidad",
    "pista": "Piensa en las dos fases que ocurren desde que percibes el peligro hasta que el vehículo se detiene.",
    "tipoPregunta": "completar"
  },
  {
    "id": "pregunta_A025",
    "number": 0,
    "enunciado": "¿Está permitido circular marcha atrás en una autopista para retomar una salida que ha pasado de largo?",
    "opciones": [
      {
        "key": "A",
        "texto": "Sí, siempre que se circule por el arcén y no se superen los 15 metros"
      },
      {
        "key": "B",
        "texto": "Sí, la marcha atrás está permitida en cualquier vía si se hace con precaución"
      },
      {
        "key": "C",
        "texto": "No, la marcha atrás está prohibida en autopistas y autovías, salvo en zonas específicamente habilitadas"
      }
    ],
    "correcta": "C",
    "explicacion": "La marcha atrás está expresamente prohibida en autopistas y autovías, salvo en zonas específicamente habilitadas para ello. Si se pasa una salida, se debe continuar hasta la siguiente.\n\n- Opciones incorrectas: ni siquiera por el arcén está permitido circular marcha atrás en autopista; la marcha atrás no está permitida en cualquier vía, tiene múltiples restricciones\n- Conexión: la marcha atrás también está prohibida en intersecciones, pasos de peatones y pasos a nivel; en cualquier caso, la distancia máxima permitida es de 15 metros\n- Error común: intentar retroceder por el arcén de la autopista para no perder una salida, lo cual es extremadamente peligroso",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_05",
    "tema": "Circulación y Velocidad",
    "pista": "En vías de alta velocidad, cualquier maniobra en sentido contrario es muy peligrosa.",
    "tipoPregunta": "directa"
  },
  {
    "id": "pregunta_A013",
    "number": 0,
    "enunciado": "Llega a una intersección sin señalizar al mismo tiempo que un tranvía que se aproxima por su izquierda. ¿Quién tiene prioridad de paso?",
    "opciones": [
      {
        "key": "A",
        "texto": "Usted, porque viene por la derecha y la prioridad corresponde siempre al que viene por la derecha sin excepciones"
      },
      {
        "key": "B",
        "texto": "El tranvía, ya que en intersecciones sin señalizar tiene prioridad sobre los demás vehículos aunque venga por la izquierda"
      },
      {
        "key": "C",
        "texto": "Ninguno de los dos; deben detenerse y esperar obligatoriamente a que un agente regule el paso"
      }
    ],
    "correcta": "B",
    "explicacion": "El tranvía tiene prioridad sobre los demás vehículos en intersecciones sin señalizar, incluso cuando se aproxima por la izquierda. Esto se debe a que no puede frenar ni maniobrar como un vehículo normal.\n\n- Opciones incorrectas: la regla de prioridad por la derecha tiene excepciones, y el tranvía es una de las más importantes; no es necesario esperar a un agente, la norma es clara sobre la prioridad del tranvía\n- Conexión: si existiera señalización de prioridad (semáforo, stop), prevalecería la señalización sobre la prioridad del tranvía\n- Error común: aplicar la regla general de prioridad por la derecha sin tener en cuenta la excepción del tranvía",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_06",
    "tema": "Prioridad y Maniobras",
    "pista": "Hay un vehículo que, por sus características, no puede frenar fácilmente.",
    "tipoPregunta": "situacional"
  },
  {
    "id": "pregunta_A014",
    "number": 0,
    "enunciado": "Circula por una carretera de montaña y llega a un estrechamiento con fuerte pendiente ascendente. Un camión desciende por el otro lado. ¿Quién tiene prioridad?",
    "opciones": [
      {
        "key": "A",
        "texto": "El camión que desciende, porque los vehículos que bajan siempre tienen prioridad en cualquier pendiente"
      },
      {
        "key": "B",
        "texto": "Usted, ya que el vehículo que asciende tiene prioridad en pendientes pronunciadas, salvo que encuentre un apartadero antes del cruce"
      },
      {
        "key": "C",
        "texto": "Ninguno tiene prioridad; deben detenerse los dos obligatoriamente"
      }
    ],
    "correcta": "B",
    "explicacion": "En estrechamientos con pendiente pronunciada, el vehículo que sube tiene prioridad porque es más difícil y peligroso arrancar cuesta arriba. La excepción es si el que sube encuentra un apartadero antes del punto de cruce.\n\n- Opciones incorrectas: el que desciende no tiene prioridad, ya que le resulta más fácil maniobrar cuesta abajo; no es obligatorio que ambos se detengan, la norma establece prioridad para el ascendente\n- Conexión: en estrechamientos sin pendiente significativa, tiene prioridad el vehículo que haya entrado primero o el que tenga más dificultad para hacer marcha atrás\n- Excepción: si el que asciende encuentra un apartadero antes del cruce, debe detenerse y dejar pasar al que baja",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_06",
    "tema": "Prioridad y Maniobras",
    "pista": "¿Para quién es más difícil arrancar de nuevo si se detiene?",
    "tipoPregunta": "directa"
  },
  {
    "id": "pregunta_A015",
    "number": 0,
    "enunciado": "Al incorporarse a la circulación desde un garaje que da a una acera con peatones, el conductor debe...",
    "opciones": [
      {
        "key": "A",
        "texto": "hacer sonar el claxon para que los peatones se aparten en todos los casos antes de salir"
      },
      {
        "key": "B",
        "texto": "salir con rapidez para nunca obstaculizar a los peatones que se acerquen"
      },
      {
        "key": "C",
        "texto": "cruzar la acera con extrema precaución, cediendo el paso a los peatones que circulen por ella"
      }
    ],
    "correcta": "C",
    "explicacion": "Al incorporarse desde una vía privada o garaje, el conductor debe cruzar la acera con extrema precaución y ceder el paso a los peatones. El conductor que se incorpora no tiene prioridad sobre los que ya circulan.\n\n- Opciones incorrectas: el claxon está prohibido en poblado salvo peligro inminente, no se usa para pedir paso; salir con rapidez es peligroso y no garantiza la seguridad de los peatones\n- Conexión: al incorporarse desde un garaje, también se debe ceder el paso a los vehículos que circulan por la vía, no solo a los peatones\n- Error común: creer que tocar el claxon es suficiente advertencia para salir de un garaje",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_06",
    "tema": "Prioridad y Maniobras",
    "pista": "Piensa en quién tiene prioridad: el que ya circula o el que se incorpora.",
    "tipoPregunta": "completar"
  },
  {
    "id": "pregunta_A016",
    "number": 0,
    "enunciado": "Circula por una carretera convencional de un carril por sentido con línea continua. Delante de usted va un ciclista. ¿Puede adelantarlo cruzando la línea continua?",
    "opciones": [
      {
        "key": "A",
        "texto": "No, la línea continua prohíbe el adelantamiento en todos los casos sin excepción"
      },
      {
        "key": "B",
        "texto": "Sí, se permite cruzar la línea continua para adelantar ciclistas si se mantiene una distancia lateral mínima de 1,5 metros y se hace con seguridad"
      },
      {
        "key": "C",
        "texto": "Sí, pero solamente si circula a menos de 30 km/h"
      }
    ],
    "correcta": "B",
    "explicacion": "Está permitido cruzar la línea continua para adelantar a ciclistas siempre que se mantenga la distancia lateral mínima de 1,5 metros y la maniobra se realice con seguridad. Esta excepción busca proteger a los ciclistas como usuarios vulnerables.\n\n- Opciones incorrectas: la línea continua sí tiene una excepción importante para ciclistas; no existe un límite de velocidad de 30 km/h como condición para esta excepción\n- Conexión: además de cruzar la línea continua, se debe reducir la velocidad en 20 km/h respecto al límite de la vía durante el adelantamiento al ciclista\n- Dato clave: la distancia lateral mínima obligatoria es de 1,5 metros en cualquier tipo de vía, tanto urbana como interurbana",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_06",
    "tema": "Prioridad y Maniobras",
    "pista": "Los ciclistas son usuarios vulnerables y la normativa les protege de forma especial.",
    "tipoPregunta": "situacional"
  },
  {
    "id": "pregunta_A017",
    "number": 0,
    "enunciado": "Va a adelantar a un ciclista en una carretera convencional cuyo límite es 90 km/h. ¿A qué velocidad máxima debe realizar el adelantamiento?",
    "opciones": [
      {
        "key": "A",
        "texto": "A 70 km/h, ya que debe reducir 20 km/h respecto al límite de la vía"
      },
      {
        "key": "B",
        "texto": "A 90 km/h, porque nunca hay que reducir la velocidad al adelantar"
      },
      {
        "key": "C",
        "texto": "A 50 km/h en cualquier circunstancia, independientemente del tipo de vía"
      }
    ],
    "correcta": "A",
    "explicacion": "Al adelantar a un ciclista, la normativa obliga a reducir la velocidad en 20 km/h respecto al límite de la vía. En una carretera convencional con límite de 90 km/h, la velocidad máxima durante el adelantamiento es de 70 km/h.\n\n- Opciones incorrectas: mantener los 90 km/h es excesivo y peligroso al pasar junto a un ciclista; no existe una velocidad fija de 50 km/h independientemente de la vía, se calcula restando 20 km/h al límite\n- Conexión: además de reducir la velocidad, se debe mantener una distancia lateral mínima de 1,5 metros\n- Dato clave: la reducción es de 20 km/h respecto al límite, no una velocidad fija",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_06",
    "tema": "Prioridad y Maniobras",
    "pista": "La reducción de velocidad se calcula restando un valor fijo al límite de la vía.",
    "tipoPregunta": "dato"
  },
  {
    "id": "pregunta_A018",
    "number": 0,
    "enunciado": "Se aproxima a un paso de peatones y ve que un peatón en la acera muestra intención manifiesta de cruzar. ¿Debe cederle el paso?",
    "opciones": [
      {
        "key": "A",
        "texto": "No, solamente cuando el peatón ya esté cruzando por el paso de peatones"
      },
      {
        "key": "B",
        "texto": "Sí, debe ceder el paso al peatón cuando muestre intención manifiesta de cruzar, aunque aún no haya pisado la calzada"
      },
      {
        "key": "C",
        "texto": "No, el peatón debe esperar siempre a que no circule ningún vehículo"
      }
    ],
    "correcta": "B",
    "explicacion": "El conductor debe ceder el paso a los peatones cuando muestren intención manifiesta de cruzar por un paso de peatones, sin esperar a que ya estén cruzando. Esto refuerza la protección de los peatones como usuarios vulnerables.\n\n- Opciones incorrectas: no hay que esperar a que el peatón esté ya en la calzada, basta con la intención manifiesta; el peatón tiene prioridad en el paso de peatones y no tiene que esperar a que no haya vehículos\n- Conexión: la sanción por no ceder el paso a un peatón en un paso de peatones es de 200 euros y 4 puntos\n- Error común: muchos conductores esperan a que el peatón ya esté cruzando, cuando la obligación surge con la intención manifiesta",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_06",
    "tema": "Prioridad y Maniobras",
    "pista": "La protección del peatón comienza antes de que pise la calzada.",
    "tipoPregunta": "directa"
  },
  {
    "id": "pregunta_A019",
    "number": 0,
    "enunciado": "Va a estacionar su turismo en una calle con pendiente ascendente y hay bordillo. ¿Hacia dónde debe girar las ruedas delanteras?",
    "opciones": [
      {
        "key": "A",
        "texto": "Hacia el centro de la vía, para que si el vehículo se desplaza las ruedas choquen con el bordillo y lo detengan"
      },
      {
        "key": "B",
        "texto": "Siempre hacia el bordillo, independientemente de si la pendiente es ascendente o descendente"
      },
      {
        "key": "C",
        "texto": "En ningún caso es necesario girar las ruedas; basta con poner el freno de mano"
      }
    ],
    "correcta": "A",
    "explicacion": "En pendiente ascendente con bordillo, las ruedas delanteras deben girarse hacia el centro de la vía. Así, si el vehículo se desplaza hacia atrás, las ruedas giran y chocan contra el bordillo, deteniendo el vehículo.\n\n- Opciones incorrectas: girar hacia el bordillo es la maniobra correcta en pendiente descendente, no ascendente; el freno de mano es obligatorio pero no suficiente como única medida\n- Conexión: en pendiente descendente, las ruedas se giran hacia el bordillo para que este las detenga si el vehículo avanza; además, se recomienda dejar la primera marcha en subida y la marcha atrás en bajada\n- Error común: confundir la dirección de las ruedas entre subida y bajada",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_06",
    "tema": "Prioridad y Maniobras",
    "pista": "Imagina hacia dónde se movería el coche si fallara el freno, y dónde las ruedas encontrarían un tope.",
    "tipoPregunta": "situacional"
  },
  {
    "id": "pregunta_A001",
    "number": 0,
    "enunciado": "Circula de noche por una carretera convencional sin iluminación. Un vehículo se acerca de frente a unos 200 metros. ¿Qué debe hacer con las luces?",
    "opciones": [
      {
        "key": "A",
        "texto": "Cambiar a luces de cruce antes de que el vehículo esté a menos de 150 metros"
      },
      {
        "key": "B",
        "texto": "Mantener siempre las luces de carretera para ver mejor en cualquier circunstancia"
      },
      {
        "key": "C",
        "texto": "Apagar todas las luces hasta que el vehículo pase"
      }
    ],
    "correcta": "A",
    "explicacion": "Debe cambiar de luces de carretera (largas) a luces de cruce (cortas) para no deslumbrar al vehículo que se aproxima de frente. La distancia de referencia es de 150 metros.\n\n- Opciones incorrectas: mantener las largas deslumbraría al otro conductor causando peligro; apagar las luces está prohibido y es extremadamente peligroso de noche\n- Conexión: si le deslumbran, debe mirar hacia el borde derecho de la vía y reducir la velocidad\n- Dato clave: la distancia de referencia para el cambio de largas a cruce es de 150 metros",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_07",
    "tema": "Señalización",
    "pista": "Piensa en la distancia a la que las luces largas empiezan a molestar al otro conductor.",
    "tipoPregunta": "directa"
  },
  {
    "id": "pregunta_A002",
    "number": 0,
    "enunciado": "Entra en un túnel bien iluminado durante el día. ¿Qué luces debe encender?",
    "opciones": [
      {
        "key": "A",
        "texto": "Luces de cruce obligatoriamente, aunque el túnel tenga buena iluminación"
      },
      {
        "key": "B",
        "texto": "Ninguna, porque el túnel está bien iluminado y no es necesario en ningún caso"
      },
      {
        "key": "C",
        "texto": "Solamente las luces de posición, ya que hay suficiente visibilidad"
      }
    ],
    "correcta": "A",
    "explicacion": "Las luces de cruce son obligatorias siempre que se circula por un túnel, independientemente de que esté bien iluminado. Es una de las situaciones donde las luces de cruce son obligatorias de día.\n\n- Opciones incorrectas: no llevar luces en un túnel es una infracción grave aunque haya iluminación; las luces de posición no son suficientes dentro de un túnel\n- Conexión: otras situaciones donde las luces de cruce son obligatorias de día son los carriles reversibles y los carriles adicionales en sentido contrario\n- Error común: muchos alumnos creen que si el túnel está iluminado no hace falta encender las luces de cruce",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_07",
    "tema": "Señalización",
    "pista": "En los túneles hay una obligación especial de alumbrado, sin excepciones.",
    "tipoPregunta": "situacional"
  },
  {
    "id": "pregunta_A003",
    "number": 0,
    "enunciado": "Si los intermitentes del vehículo no funcionan, para indicar un giro a la derecha con el brazo, el conductor debe...",
    "opciones": [
      {
        "key": "A",
        "texto": "extender el brazo izquierdo horizontalmente siempre que circule"
      },
      {
        "key": "B",
        "texto": "extender el brazo izquierdo moviéndolo de arriba a abajo"
      },
      {
        "key": "C",
        "texto": "extender el brazo izquierdo doblado hacia arriba"
      }
    ],
    "correcta": "C",
    "explicacion": "Para señalizar un giro a la derecha con el brazo, el conductor extiende el brazo izquierdo doblado hacia arriba. Es una señal obligatoria cuando fallan los intermitentes.\n\n- Opciones incorrectas: el brazo extendido horizontalmente indica giro a la izquierda; el movimiento de arriba a abajo indica que va a frenar o reducir velocidad\n- Conexión: las señales con el brazo también se usan en bicicletas y ciclomotores donde no haya intermitentes\n- Error común: confundir la señal de giro a la derecha (brazo doblado arriba) con la de giro a la izquierda (brazo extendido horizontal)",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_07",
    "tema": "Señalización",
    "pista": "Es el brazo izquierdo el que se saca por la ventanilla, ya que en España se conduce por la derecha.",
    "tipoPregunta": "completar"
  },
  {
    "id": "pregunta_A004",
    "number": 0,
    "enunciado": "Un semáforo indica verde, pero un agente de tráfico situado en la intersección le ordena detenerse con el brazo levantado. ¿A quién debe obedecer?",
    "opciones": [
      {
        "key": "A",
        "texto": "Al agente, ya que sus indicaciones prevalecen sobre los semáforos"
      },
      {
        "key": "B",
        "texto": "Al semáforo, porque sus indicaciones prevalecen siempre sobre las de los agentes"
      },
      {
        "key": "C",
        "texto": "A ninguno de los dos; debe detenerse solamente si hay peligro evidente"
      }
    ],
    "correcta": "A",
    "explicacion": "Las señales de los agentes de tráfico tienen la máxima prioridad en la jerarquía de señalización, por encima de semáforos, señales verticales y marcas viales.\n\n- Opciones incorrectas: el semáforo nunca prevalece sobre el agente; detenerse solo ante peligro evidente ignora la obligación de obedecer al agente\n- Conexión: la jerarquía completa es: 1) agentes, 2) señalización circunstancial (obras), 3) semáforos, 4) señales verticales, 5) marcas viales\n- Dato clave: el agente con el brazo levantado verticalmente equivale a semáforo en rojo para todas las direcciones",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_07",
    "tema": "Señalización",
    "pista": "Recuerda la jerarquía de señales: ¿quién manda más, una persona o un aparato?",
    "tipoPregunta": "directa"
  },
  {
    "id": "pregunta_A005",
    "number": 0,
    "enunciado": "Un agente de tráfico utiliza el silbato emitiendo un toque largo. ¿Qué debe hacer?",
    "opciones": [
      {
        "key": "A",
        "texto": "Detenerse inmediatamente, ya que cualquier toque de silbato indica parada obligatoria"
      },
      {
        "key": "B",
        "texto": "Continuar la marcha, porque el toque largo indica vía libre"
      },
      {
        "key": "C",
        "texto": "Reducir la velocidad solamente y esperar otra indicación"
      }
    ],
    "correcta": "B",
    "explicacion": "Un toque largo de silbato del agente significa reanudar la marcha o vía libre. Es al contrario de lo que muchos alumnos intuyen.\n\n- Opciones incorrectas: detenerse correspondería a toques cortos y frecuentes, no a un toque largo; reducir la velocidad sin más no es la respuesta al toque largo\n- Conexión: el truco para recordarlo es LARGO = largo camino por delante = circular; CORTOS = cortar la marcha = parar\n- Error común: esta es una de las preguntas trampa más frecuentes del examen, ya que intuitivamente se asocia un toque largo con algo importante como detenerse",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_07",
    "tema": "Señalización",
    "pista": "La relación entre la duración del toque y su significado es al revés de lo que parece lógico.",
    "tipoPregunta": "directa"
  },
  {
    "id": "pregunta_A006",
    "number": 0,
    "enunciado": "Se encuentra en una intersección regulada por semáforo. La luz amarilla está en intermitente. ¿Cómo debe actuar?",
    "opciones": [
      {
        "key": "A",
        "texto": "Detenerse obligatoriamente en todos los casos, como si fuera un semáforo en rojo"
      },
      {
        "key": "B",
        "texto": "Continuar sin reducir la velocidad, porque el amarillo intermitente nunca obliga a nada"
      },
      {
        "key": "C",
        "texto": "Extremar la precaución y aplicar las normas generales de prioridad, ya que no hay regulación semafórica activa"
      }
    ],
    "correcta": "C",
    "explicacion": "El semáforo en amarillo intermitente indica que no hay regulación semafórica activa. El conductor debe extremar la precaución y aplicar las normas generales de prioridad de paso (prioridad por la derecha, señales de ceda el paso o stop si existen).\n\n- Opciones incorrectas: no es obligatorio detenerse como con un rojo, sino aplicar las normas de prioridad; continuar sin precaución es peligroso porque la intersección no está regulada\n- Conexión: el rojo intermitente sí equivale a un stop, lo que genera confusión con el amarillo intermitente\n- Error común: confundir amarillo intermitente (precaución, aplicar prioridad) con rojo intermitente (stop obligatorio)",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_07",
    "tema": "Señalización",
    "pista": "El amarillo intermitente no prohíbe el paso, pero advierte de algo.",
    "tipoPregunta": "situacional"
  },
  {
    "id": "pregunta_A007",
    "number": 0,
    "enunciado": "La señal R-303 (giro a la izquierda prohibido) también prohíbe...",
    "opciones": [
      {
        "key": "A",
        "texto": "solamente el giro a la izquierda, no afecta a ninguna otra maniobra"
      },
      {
        "key": "B",
        "texto": "el cambio de sentido, además del giro a la izquierda"
      },
      {
        "key": "C",
        "texto": "el adelantamiento en cualquier circunstancia"
      }
    ],
    "correcta": "B",
    "explicacion": "La señal R-303 prohíbe tanto el giro a la izquierda como el cambio de sentido. Esto se debe a que para realizar un cambio de sentido normalmente se inicia girando a la izquierda.\n\n- Opciones incorrectas: la R-303 no prohíbe solo el giro a la izquierda, también el cambio de sentido; el adelantamiento tiene su propia señal de prohibición (R-305)\n- Conexión: la señal R-304 es específica para prohibir la media vuelta (cambio de sentido), pero la R-303 también implica esa prohibición\n- Error común: pensar que la R-303 solo prohíbe girar a la izquierda y que se puede hacer cambio de sentido",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_07",
    "tema": "Señalización",
    "pista": "Piensa en qué maniobra comienza igual que un giro a la izquierda.",
    "tipoPregunta": "completar"
  },
  {
    "id": "pregunta_A008",
    "number": 0,
    "enunciado": "Circula por una carretera convencional y ve una señal triangular con borde rojo que muestra la silueta de un ciclista. ¿Qué indica esta señal?",
    "opciones": [
      {
        "key": "A",
        "texto": "Advierte de la posible presencia de ciclistas en la vía, por lo que debe extremar la precaución"
      },
      {
        "key": "B",
        "texto": "Prohíbe en todo caso la circulación de ciclistas por esa vía"
      },
      {
        "key": "C",
        "texto": "Obliga exclusivamente a los ciclistas a circular por esa vía"
      }
    ],
    "correcta": "A",
    "explicacion": "La señal P-22 es una señal de advertencia de peligro (triángulo con borde rojo) que indica la posible presencia de ciclistas en la vía. No prohíbe ni obliga nada, solo advierte para que se extreme la precaución.\n\n- Opciones incorrectas: las señales de peligro (triángulo rojo) no prohíben ni obligan, solo advierten; las señales de prohibición son circulares con borde rojo, y las de obligación son circulares con fondo azul\n- Conexión: al adelantar a los ciclistas se debe mantener una distancia lateral mínima de 1,5 metros y se puede cruzar la línea continua si es necesario\n- Dato clave: las señales triangulares con borde rojo son siempre de advertencia de peligro",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_07",
    "tema": "Señalización",
    "pista": "Fíjate en la forma de la señal: los triángulos advierten, los círculos prohíben u obligan.",
    "tipoPregunta": "situacional"
  },
  {
    "id": "pregunta_A009",
    "number": 0,
    "enunciado": "Circula por una carretera convencional de un carril por sentido. A su izquierda hay una línea continua y a su derecha una discontinua. ¿Puede adelantar al vehículo que le precede?",
    "opciones": [
      {
        "key": "A",
        "texto": "No, porque la línea continua de su lado prohíbe invadir el carril contrario, salvo para adelantar ciclistas manteniendo 1,5 metros"
      },
      {
        "key": "B",
        "texto": "Sí, siempre que no venga ningún vehículo de frente en ningún caso"
      },
      {
        "key": "C",
        "texto": "Sí, ya que la línea discontinua del otro lado le autoriza a adelantar en cualquier circunstancia"
      }
    ],
    "correcta": "A",
    "explicacion": "Cuando la marca vial de su lado es una línea continua, está prohibido cruzarla para adelantar. La única excepción es el adelantamiento a ciclistas, donde se permite cruzar la línea continua si es necesario para mantener la distancia de 1,5 metros.\n\n- Opciones incorrectas: lo que importa es la línea de su lado (continua = no cruzar), no la del lado contrario; la línea discontinua del otro lado solo autoriza a los vehículos que circulan en sentido contrario\n- Conexión: en las marcas de continua + discontinua, cada conductor debe fijarse en la línea que tiene a su lado\n- Error común: mirar la línea del lado contrario y creer que autoriza a adelantar desde ambos sentidos",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_07",
    "tema": "Señalización",
    "pista": "Lo que cuenta es la línea que está de tu lado, no la del carril contrario.",
    "tipoPregunta": "directa"
  },
  {
    "id": "pregunta_A010",
    "number": 0,
    "enunciado": "Una marca vial de cuadrícula amarilla pintada en una intersección indica que...",
    "opciones": [
      {
        "key": "A",
        "texto": "se trata de una zona de estacionamiento reservado exclusivamente para residentes"
      },
      {
        "key": "B",
        "texto": "los peatones tienen prohibido cruzar en todos los casos por esa zona"
      },
      {
        "key": "C",
        "texto": "no se debe bloquear esa zona, aunque el semáforo esté en verde"
      }
    ],
    "correcta": "C",
    "explicacion": "La cuadrícula amarilla pintada en una intersección indica que no se debe invadir ni bloquear esa zona, aunque el semáforo esté en verde. Si prevemos que no podremos salir de la intersección, no debemos entrar en ella.\n\n- Opciones incorrectas: la cuadrícula amarilla no es zona de estacionamiento para residentes, que se marca con líneas verdes en el bordillo; no tiene relación con la prohibición de paso de peatones\n- Conexión: el objetivo es evitar bloquear intersecciones y mantener el flujo de tráfico, especialmente en zonas de alta congestión\n- Error común: entrar en la cuadrícula amarilla porque el semáforo está en verde, sin prever que el tráfico impedirá salir",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_07",
    "tema": "Señalización",
    "pista": "Esta marca protege el flujo de tráfico en las intersecciones.",
    "tipoPregunta": "completar"
  },
  {
    "id": "pregunta_A011",
    "number": 0,
    "enunciado": "Se encuentra con una zona de obras señalizada con señales de fondo amarillo que limitan la velocidad a 60 km/h. Sin embargo, una señal vertical permanente indica un límite de 80 km/h. ¿Qué límite debe respetar?",
    "opciones": [
      {
        "key": "A",
        "texto": "El de 80 km/h, ya que las señales permanentes prevalecen siempre sobre las temporales"
      },
      {
        "key": "B",
        "texto": "Puede elegir cualquiera de los dos límites según su criterio"
      },
      {
        "key": "C",
        "texto": "El de 60 km/h, porque la señalización circunstancial de obras prevalece sobre la permanente"
      }
    ],
    "correcta": "C",
    "explicacion": "La señalización circunstancial (obras, accidentes) prevalece sobre la señalización permanente en la jerarquía de señales. Las señales temporales de fondo amarillo indican condiciones específicas de la vía en ese momento.\n\n- Opciones incorrectas: las señales permanentes no prevalecen sobre las temporales, es al revés; el conductor no puede elegir según su criterio, debe obedecer la señal de mayor jerarquía\n- Conexión: en la jerarquía de señales, la señalización circunstancial está por debajo de los agentes pero por encima de los semáforos, señales verticales y marcas viales\n- Dato clave: la jerarquía es: 1) agentes, 2) circunstancial, 3) semáforos, 4) verticales, 5) marcas viales",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_07",
    "tema": "Señalización",
    "pista": "Las señales temporales existen por una razón concreta de seguridad.",
    "tipoPregunta": "directa"
  },
  {
    "id": "pregunta_A012",
    "number": 0,
    "enunciado": "Circula de noche por un túnel y observa captafaros de color azul. ¿Qué le indican?",
    "opciones": [
      {
        "key": "A",
        "texto": "La proximidad de una salida de emergencia en el túnel"
      },
      {
        "key": "B",
        "texto": "Que se encuentra en el borde derecho de la calzada en cualquier tipo de vía"
      },
      {
        "key": "C",
        "texto": "Que la vía está cerrada por obras obligatoriamente"
      }
    ],
    "correcta": "A",
    "explicacion": "Los captafaros de color azul se utilizan para señalizar las salidas de emergencia en túneles, siendo una referencia visual importante en caso de evacuación o incendio.\n\n- Opciones incorrectas: el borde derecho de la calzada se señaliza con captafaros blancos o amarillos, no azules; los captafaros azules no indican cierre por obras\n- Conexión: los captafaros blancos/amarillos indican el borde derecho, los blancos el borde izquierdo, y los amarillos/naranja las medianas o separadores\n- Error común: no conocer el significado del color azul en los captafaros, que es específico de túneles",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_07",
    "tema": "Señalización",
    "pista": "Piensa en qué lugar subterráneo necesitarías encontrar una salida rápidamente.",
    "tipoPregunta": "directa"
  },
  {
    "id": "pregunta_B013",
    "number": 0,
    "enunciado": "Circulando por una autovía, se ha pasado de la salida que debía tomar. ¿Qué debe hacer?",
    "opciones": [
      {
        "key": "A",
        "texto": "Continuar hasta la siguiente salida y volver desde allí"
      },
      {
        "key": "B",
        "texto": "Dar marcha atrás por el arcén hasta la salida"
      },
      {
        "key": "C",
        "texto": "Detenerse en el arcén y esperar a que no venga tráfico para retroceder"
      }
    ],
    "correcta": "A",
    "explicacion": "Si se pasa de la salida en una autovía o autopista, lo único correcto, seguro y legal es continuar hasta la siguiente salida. Dar marcha atrás, detenerse en el arcén o cruzar la mediana están terminantemente prohibidos.\n\n- Opciones incorrectas: dar marcha atrás por el arcén es extremadamente peligroso y está prohibido; detenerse en el arcén para retroceder tampoco está permitido y supone un grave riesgo\n- Conexión: en autopistas y autovías está prohibido dar marcha atrás, detenerse salvo emergencia y cambiar de sentido fuera de las áreas habilitadas\n- Error común: muchos conductores se ponen nerviosos al pasarse de salida e intentan maniobras peligrosas en lugar de asumir los kilómetros de más",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_08",
    "tema": "Situaciones Especiales",
    "pista": "Piensa en cuál es la única maniobra segura cuando no hay forma de retroceder.",
    "tipoPregunta": "situacional"
  },
  {
    "id": "pregunta_B014",
    "number": 0,
    "enunciado": "Se produce un incendio dentro de un túnel y no puede mover su vehículo. ¿Qué debe hacer con las llaves?",
    "opciones": [
      {
        "key": "A",
        "texto": "Dejarlas puestas en el contacto o dentro del vehículo y no cerrar con llave"
      },
      {
        "key": "B",
        "texto": "Llevárselas consigo para evitar que le roben el vehículo"
      },
      {
        "key": "C",
        "texto": "Guardarlas en la guantera y cerrar el vehículo con llave"
      }
    ],
    "correcta": "A",
    "explicacion": "En caso de incendio en un túnel, si no puede mover el vehículo, debe dejar las llaves puestas en el contacto y no cerrar con llave. Esto permite que los bomberos puedan mover el vehículo si es necesario para facilitar la evacuación o la extinción.\n\n- Opciones incorrectas: llevarse las llaves impediría a los servicios de emergencia mover el vehículo; cerrar con llave dificultaría aún más la labor de bomberos y rescatistas\n- Conexión: tras dejar las llaves, debe abandonar el vehículo y dirigirse a las salidas de emergencia señalizadas con luz verde, caminando agachado porque el humo sube\n- Error común: el instinto de proteger el vehículo puede llevar a cerrar con llave, pero en una emergencia la prioridad es facilitar el acceso a los servicios de rescate",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_08",
    "tema": "Situaciones Especiales",
    "pista": "Los servicios de emergencia pueden necesitar acceder al vehículo.",
    "tipoPregunta": "situacional"
  },
  {
    "id": "pregunta_B015",
    "number": 0,
    "enunciado": "Se aproxima a un paso a nivel sin barreras y su vehículo se cala sobre las vías. ¿Cuál debe ser su primera acción?",
    "opciones": [
      {
        "key": "A",
        "texto": "Intentar arrancar el motor en primera marcha, ya que el motor de arranque puede desplazar el vehículo unos metros"
      },
      {
        "key": "B",
        "texto": "Abandonar inmediatamente el vehículo sin intentar nada más"
      },
      {
        "key": "C",
        "texto": "Esperar dentro del vehículo hasta que llegue ayuda profesional"
      }
    ],
    "correcta": "A",
    "explicacion": "Si el motor se cala sobre las vías de un paso a nivel, lo primero es intentar arrancar con el motor de arranque en primera marcha, que puede mover el vehículo unos metros fuera de las vías. Si esto no funciona, entonces sí hay que sacar a todos los ocupantes inmediatamente.\n\n- Opciones incorrectas: abandonar sin intentar arrancar puede ser prematuro si el motor de arranque puede resolver la situación en segundos; esperar dentro del vehículo es extremadamente peligroso porque un tren necesita más de 1 km para detenerse\n- Conexión: un tren a 100 km/h necesita más de 1 kilómetro para detenerse completamente, por lo que nunca debe subestimarse su velocidad de aproximación\n- Error común: entrar en pánico y no recordar que el motor de arranque puede mover el vehículo",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_08",
    "tema": "Situaciones Especiales",
    "pista": "El motor de arranque tiene una función que puede salvarle en esta situación.",
    "tipoPregunta": "directa"
  },
  {
    "id": "pregunta_B016",
    "number": 0,
    "enunciado": "Al comenzar a llover, los primeros minutos son especialmente peligrosos porque...",
    "opciones": [
      {
        "key": "A",
        "texto": "el agua se mezcla con el polvo, la grasa y el aceite acumulados en el asfalto, reduciendo mucho la adherencia"
      },
      {
        "key": "B",
        "texto": "la visibilidad se reduce drásticamente y es obligatorio detenerse"
      },
      {
        "key": "C",
        "texto": "siempre se produce aquaplaning desde el primer momento"
      }
    ],
    "correcta": "A",
    "explicacion": "Los primeros minutos de lluvia son los más peligrosos porque el agua se mezcla con los restos de polvo, grasa y aceite acumulados en el asfalto, creando una película muy resbaladiza que reduce la adherencia más que cuando la lluvia ya ha limpiado la superficie.\n\n- Opciones incorrectas: la segunda exagera al decir que es obligatorio detenerse; la tercera afirma que siempre hay aquaplaning cuando este se produce con acumulación de agua y velocidades superiores a 80 km/h aproximadamente\n- Conexión: con pavimento mojado la distancia de frenado se duplica, por lo que la distancia de seguridad debe aumentarse a un mínimo de 3 segundos\n- Dato clave: distancia de frenado en mojado = el doble que en seco; distancia de seguridad mínima en lluvia = 3 segundos",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_08",
    "tema": "Situaciones Especiales",
    "pista": "Piensa en lo que se acumula sobre el asfalto entre períodos de lluvia.",
    "tipoPregunta": "completar"
  },
  {
    "id": "pregunta_B018",
    "number": 0,
    "enunciado": "Circula por una vía urbana y un vehículo de emergencia se aproxima por detrás con señales luminosas y acústicas activadas. ¿Qué debe hacer?",
    "opciones": [
      {
        "key": "A",
        "texto": "Apartarse a la derecha y, si es necesario, reducir la velocidad o detenerse para facilitar el paso"
      },
      {
        "key": "B",
        "texto": "Detenerse inmediatamente donde esté, sin moverse"
      },
      {
        "key": "C",
        "texto": "Acelerar para no entorpecer y apartarse cuando pueda"
      }
    ],
    "correcta": "A",
    "explicacion": "Ante un vehículo de emergencia con señales activadas, debe apartarse a la derecha y reducir la velocidad o detenerse si es necesario para facilitar su paso. Hay que mantener la calma y mirar los retrovisores para localizar de dónde viene.\n\n- Opciones incorrectas: detenerse inmediatamente donde se esté podría bloquear el paso del vehículo de emergencia; acelerar es peligroso y contrario al protocolo de actuación\n- Conexión: está prohibido seguir al vehículo de emergencia aprovechando el camino que abre entre el tráfico\n- Excepción: si está detenido en un semáforo en rojo, puede avanzar ligeramente con extrema precaución si es necesario para dejar paso",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_08",
    "tema": "Situaciones Especiales",
    "pista": "La clave es facilitar el paso sin crear nuevos peligros.",
    "tipoPregunta": "situacional"
  },
  {
    "id": "pregunta_B022",
    "number": 0,
    "enunciado": "Circula por un descenso prolongado de montaña y nota que el pedal de freno se vuelve esponjoso. ¿Qué le está ocurriendo a los frenos?",
    "opciones": [
      {
        "key": "A",
        "texto": "Están sufriendo fading por sobrecalentamiento debido al uso excesivo del pedal de freno"
      },
      {
        "key": "B",
        "texto": "Es normal en bajadas y no indica ningún problema"
      },
      {
        "key": "C",
        "texto": "Significa que el líquido de frenos se ha agotado totalmente"
      }
    ],
    "correcta": "A",
    "explicacion": "El fading es la pérdida de eficacia de los frenos por sobrecalentamiento, que ocurre al usar excesivamente el pedal de freno en descensos prolongados. El pedal se vuelve esponjoso y hay que pisar más para conseguir el mismo efecto de frenado.\n\n- Opciones incorrectas: no es normal ni aceptable que los frenos pierdan eficacia; aunque una fuga de líquido de frenos también reduce la frenada, los síntomas descritos son típicos de fading por sobrecalentamiento\n- Conexión: la prevención del fading consiste en usar marchas cortas en bajadas largas para aprovechar el freno motor, evitando mantener el pie en el pedal de freno constantemente\n- Error común: si ocurre el fading, nunca se debe echar agua fría sobre los frenos porque puede agrietar los discos",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_09",
    "tema": "Seguridad y Tecnología",
    "pista": "El uso continuado de los frenos genera calor, y el calor excesivo tiene consecuencias.",
    "tipoPregunta": "directa"
  },
  {
    "id": "pregunta_B023",
    "number": 0,
    "enunciado": "Su vehículo dispone de frenada automática de emergencia (AEB). ¿Puede confiar plenamente en este sistema y reducir su atención a la conducción?",
    "opciones": [
      {
        "key": "A",
        "texto": "No, el AEB es una ayuda que no sustituye la atención del conductor"
      },
      {
        "key": "B",
        "texto": "Sí, ya que el sistema frena automáticamente ante cualquier obstáculo"
      },
      {
        "key": "C",
        "texto": "Sí, siempre que el sistema esté activado y funcionando correctamente"
      }
    ],
    "correcta": "A",
    "explicacion": "El AEB, como todos los sistemas ADAS, es una ayuda a la conducción que no sustituye al conductor. El conductor debe mantener siempre el control del vehículo y estar preparado para actuar si el sistema falla o no detecta un obstáculo.\n\n- Opciones incorrectas: la segunda afirma que el sistema frena ante cualquier obstáculo, lo cual es falso porque tiene limitaciones técnicas; la tercera sugiere que basta con que esté activado para desentenderse, cuando la responsabilidad sigue siendo del conductor\n- Conexión: los ADAS corresponden a los niveles 1 y 2 de automatización; el conductor es siempre responsable legalmente\n- Error común: confiar excesivamente en los sistemas de ayuda y reducir la atención, lo que puede provocar accidentes cuando el sistema no reacciona como se espera",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_09",
    "tema": "Seguridad y Tecnología",
    "pista": "La tecnología del vehículo tiene limitaciones que el conductor debe conocer.",
    "tipoPregunta": "directa"
  },
  {
    "id": "pregunta_B024",
    "number": 0,
    "enunciado": "El testigo de aceite del cuadro de instrumentos se enciende en color rojo mientras conduce. Esto significa que...",
    "opciones": [
      {
        "key": "A",
        "texto": "debe detener el vehículo inmediatamente para evitar daños graves en el motor"
      },
      {
        "key": "B",
        "texto": "puede continuar conduciendo hasta el taller más cercano sin urgencia"
      },
      {
        "key": "C",
        "texto": "solamente necesita revisar el nivel de aceite en la próxima parada programada"
      }
    ],
    "correcta": "A",
    "explicacion": "El testigo de aceite en rojo indica una emergencia que requiere detener el vehículo inmediatamente. Continuar conduciendo sin presión de aceite puede causar el gripado del motor, un daño irreversible y muy costoso.\n\n- Opciones incorrectas: continuar hasta un taller puede causar daños irreversibles en el motor; posponer la revisión a la próxima parada puede ser demasiado tarde si hay una fuga o falta grave de aceite\n- Conexión: el testigo rojo de temperatura también requiere detenerse inmediatamente por riesgo de sobrecalentamiento del motor\n- Error común: subestimar la gravedad de los testigos rojos del cuadro de instrumentos, que siempre indican una situación que requiere actuación inmediata",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_09",
    "tema": "Seguridad y Tecnología",
    "pista": "Los testigos rojos del cuadro de instrumentos indican situaciones de máxima urgencia.",
    "tipoPregunta": "completar"
  },
  {
    "id": "pregunta_A026",
    "number": 0,
    "enunciado": "Le paran en un control de alcoholemia y usted se niega a realizar la prueba de aire espirado. ¿Qué consecuencias tiene esta negativa?",
    "opciones": [
      {
        "key": "A",
        "texto": "Una multa administrativa, pero ninguna consecuencia penal en ningún caso"
      },
      {
        "key": "B",
        "texto": "Se considera delito penal, con pena de prisión de 6 meses a 1 año y retirada del permiso"
      },
      {
        "key": "C",
        "texto": "Solamente le obligan a repetir la prueba más adelante, sin sanción adicional"
      }
    ],
    "correcta": "B",
    "explicacion": "Negarse a someterse a las pruebas de alcoholemia constituye un delito penal tipificado en el artículo 383 del Código Penal, con pena de prisión de 6 meses a 1 año y retirada del permiso de conducir de 1 a 4 años.\n\n- Opciones incorrectas: la negativa no es solo administrativa, es un delito penal; no existe la opción de repetir la prueba más adelante sin sanción\n- Conexión: negarse a la prueba puede ser incluso más grave que dar positivo en muchos casos, ya que la pena de prisión es obligatoria sin alternativa de multa o trabajos comunitarios\n- Error común: creer que negarse es menos grave que dar positivo, cuando en realidad es un delito independiente",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_10",
    "tema": "Factores de Riesgo",
    "pista": "Piensa en qué ocurre cuando alguien obstaculiza la labor de las autoridades.",
    "tipoPregunta": "situacional"
  },
  {
    "id": "pregunta_A027",
    "number": 0,
    "enunciado": "Un medicamento que ha tomado lleva un pictograma con un triángulo rojo y la silueta de un coche en la caja. ¿Qué debe hacer antes de conducir?",
    "opciones": [
      {
        "key": "A",
        "texto": "Conducir con total normalidad, porque ese símbolo nunca indica peligro real para la conducción"
      },
      {
        "key": "B",
        "texto": "Tomar una dosis menor del medicamento, lo que elimina en todos los casos cualquier efecto sobre la conducción"
      },
      {
        "key": "C",
        "texto": "Consultar al médico o farmacéutico y leer el prospecto, ya que ese pictograma indica que puede afectar a la conducción"
      }
    ],
    "correcta": "C",
    "explicacion": "El pictograma de un triángulo rojo con la silueta de un coche en el envase de un medicamento indica que puede afectar a la capacidad de conducción. Antes de conducir, se debe consultar al médico o farmacéutico y leer detenidamente el prospecto.\n\n- Opciones incorrectas: ignorar el pictograma es peligroso, ya que muchos medicamentos causan somnolencia, mareos o alteraciones de los reflejos; reducir la dosis por cuenta propia no garantiza eliminar los efectos y la automedicación es desaconsejable\n- Conexión: medicamentos como ansiolíticos, antihistamínicos, antidepresivos y analgésicos potentes son los que más frecuentemente afectan a la conducción\n- Error común: automedicarse o ajustar la dosis sin consultar al profesional sanitario",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_10",
    "tema": "Factores de Riesgo",
    "pista": "Los pictogramas en los medicamentos tienen un propósito de seguridad importante.",
    "tipoPregunta": "directa"
  },
  {
    "id": "pregunta_A028",
    "number": 0,
    "enunciado": "Para prevenir la fatiga en un viaje largo, se recomienda realizar paradas de descanso...",
    "opciones": [
      {
        "key": "A",
        "texto": "solamente cuando el conductor note síntomas evidentes de sueño"
      },
      {
        "key": "B",
        "texto": "cada 2 horas de conducción o cada 200 kilómetros aproximadamente"
      },
      {
        "key": "C",
        "texto": "cada 4 horas obligatoriamente, sin necesidad de parar antes en ningún caso"
      }
    ],
    "correcta": "B",
    "explicacion": "Se recomienda no conducir más de 2 horas seguidas y realizar paradas cada 2 horas o 200 kilómetros, donde conviene estirar las piernas e hidratarse. La prevención es clave antes de que aparezcan los síntomas.\n\n- Opciones incorrectas: esperar a notar síntomas de sueño es peligroso, ya que los microsueños pueden producirse sin que el conductor sea consciente; 4 horas es demasiado tiempo sin descanso\n- Conexión: si aparece sueño durante la conducción, lo más eficaz es detenerse en un lugar seguro y dormir una siesta de 15-20 minutos; el café tarda unos 30 minutos en hacer efecto y no sustituye al descanso\n- Dato clave: las horas de mayor riesgo de fatiga son la madrugada (2:00-6:00) y la sobremesa (14:00-16:00)",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_10",
    "tema": "Factores de Riesgo",
    "pista": "La prevención de la fatiga tiene una frecuencia recomendada, no se espera a los síntomas.",
    "tipoPregunta": "completar"
  },
  {
    "id": "pregunta_A029",
    "number": 0,
    "enunciado": "Mientras conduce, mira el móvil durante 2 segundos a 120 km/h en una autovía. ¿Cuántos metros recorre aproximadamente sin mirar la carretera?",
    "opciones": [
      {
        "key": "A",
        "texto": "Aproximadamente 67 metros, una distancia en la que pueden ocurrir muchas situaciones de peligro"
      },
      {
        "key": "B",
        "texto": "Aproximadamente 10 metros solamente, una distancia que no supone ningún riesgo real"
      },
      {
        "key": "C",
        "texto": "Aproximadamente 200 metros en todos los casos a esa velocidad"
      }
    ],
    "correcta": "A",
    "explicacion": "A 120 km/h se recorren aproximadamente 33 metros por segundo. En 2 segundos, el vehículo avanza unos 67 metros sin que el conductor mire la carretera, distancia más que suficiente para que se produzca un accidente.\n\n- Opciones incorrectas: 10 metros es una distancia muy inferior a la real, lo que da una falsa sensación de seguridad; 200 metros es una exageración que no se corresponde con el cálculo\n- Conexión: la sanción por usar el móvil sujetándolo con la mano es de 200 euros y 6 puntos, siendo una infracción muy grave\n- Dato clave: a 50 km/h en ciudad, 2 segundos equivalen a unos 28 metros sin mirar la carretera",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_10",
    "tema": "Factores de Riesgo",
    "pista": "A 120 km/h se recorren unos 33 metros cada segundo.",
    "tipoPregunta": "dato"
  },
  {
    "id": "pregunta_A030",
    "number": 0,
    "enunciado": "Conduce de vuelta a casa después de una discusión fuerte con un familiar. Nota que está muy enfadado y tenso al volante. ¿Qué debería hacer?",
    "opciones": [
      {
        "key": "A",
        "texto": "Detenerse en un lugar seguro hasta recuperar la calma, ya que las emociones intensas afectan a la conducción"
      },
      {
        "key": "B",
        "texto": "Continuar conduciendo sin parar nunca, ya que enfadarse no afecta en ningún caso a la capacidad de conducir"
      },
      {
        "key": "C",
        "texto": "Conducir más rápido para llegar antes a casa y solamente así aliviar el estrés cuanto antes"
      }
    ],
    "correcta": "A",
    "explicacion": "Los estados emocionales intensos como la ira, el estrés o la ansiedad reducen la atención, provocan decisiones precipitadas y pueden llevar a una conducción agresiva. Lo recomendable es detenerse hasta recuperar la calma.\n\n- Opciones incorrectas: el enfado sí afecta gravemente a la conducción, provocando menor atención y mayor asunción de riesgos; conducir más rápido bajo un estado emocional alterado multiplica el peligro\n- Conexión: otros factores de riesgo emocionales son la euforia excesiva, la tristeza y la prisa, todos ellos reducen la capacidad de concentración\n- Error común: creer que las emociones fuertes no afectan a la conducción o que se pueden controlar fácilmente mientras se conduce",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_10",
    "tema": "Factores de Riesgo",
    "pista": "Las emociones intensas actúan como una distracción cognitiva importante.",
    "tipoPregunta": "situacional"
  },
  {
    "id": "pregunta_B025",
    "number": 0,
    "enunciado": "Un conductor novel con 1 año de antigüedad del permiso B es sometido a un control de alcoholemia. ¿Cuál es la tasa máxima permitida en aire espirado?",
    "opciones": [
      {
        "key": "A",
        "texto": "0,15 mg/l"
      },
      {
        "key": "B",
        "texto": "0,25 mg/l"
      },
      {
        "key": "C",
        "texto": "0,30 mg/l"
      }
    ],
    "correcta": "A",
    "explicacion": "Los conductores noveles, con menos de 2 años de antigüedad del permiso, tienen una tasa máxima permitida de 0,15 mg/l en aire espirado, equivalente a 0,3 g/l en sangre. Esta tasa es inferior a la del conductor general.\n\n- Opciones incorrectas: 0,25 mg/l es la tasa general para conductores con más de 2 años de experiencia; 0,30 mg/l no corresponde a ninguna tasa en aire espirado, aunque sí es la tasa de sangre para noveles\n- Conexión: la misma tasa reducida de 0,15 mg/l aplica también a los conductores profesionales (taxi, autobús, mercancías peligrosas)\n- Dato clave: novel y profesional = 0,15 mg/l aire o 0,3 g/l sangre; general = 0,25 mg/l aire o 0,5 g/l sangre",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_10",
    "tema": "Factores de Riesgo",
    "pista": "Los conductores con menos experiencia tienen límites más estrictos.",
    "tipoPregunta": "dato"
  },
  {
    "id": "pregunta_B026",
    "number": 0,
    "enunciado": "Presencia un accidente en una carretera interurbana. ¿Qué es lo primero que debe hacer según la conducta PAS?",
    "opciones": [
      {
        "key": "A",
        "texto": "Proteger: señalizar la zona, ponerse el chaleco reflectante y activar la V-16"
      },
      {
        "key": "B",
        "texto": "Socorrer: atender inmediatamente a las víctimas antes de cualquier otra acción"
      },
      {
        "key": "C",
        "texto": "Avisar: llamar al 112 sin bajarse del vehículo"
      }
    ],
    "correcta": "A",
    "explicacion": "La conducta PAS establece un orden: primero Proteger (señalizar y asegurar la zona), después Avisar (llamar al 112) y finalmente Socorrer (atender a las víctimas). Ponerse el chaleco reflectante antes de salir del vehículo y activar la V-16 son las primeras acciones.\n\n- Opciones incorrectas: socorrer sin proteger primero puede crear nuevas víctimas si otros vehículos no ven el accidente; avisar sin proteger primero también pone en riesgo a todos los presentes\n- Conexión: la baliza V-16 es obligatoria desde enero de 2026 en vías interurbanas y es más segura que los triángulos porque no obliga a caminar por la calzada\n- Error común: el impulso natural es socorrer primero, pero la protección de la zona es prioritaria para evitar nuevos accidentes",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_11",
    "tema": "Accidentes, Emergencias y Medio Ambiente",
    "pista": "El orden de las letras P, A y S indica la secuencia correcta de actuación.",
    "tipoPregunta": "directa"
  },
  {
    "id": "pregunta_B027",
    "number": 0,
    "enunciado": "Para reducir el consumo de combustible, ¿a qué régimen de revoluciones conviene cambiar de marcha en un motor de gasolina?",
    "opciones": [
      {
        "key": "A",
        "texto": "Entre 2.000 y 2.500 rpm"
      },
      {
        "key": "B",
        "texto": "Siempre por encima de 3.500 rpm"
      },
      {
        "key": "C",
        "texto": "No importa el régimen, solo la velocidad del vehículo"
      }
    ],
    "correcta": "A",
    "explicacion": "En conducción eficiente, se recomienda cambiar a marchas largas pronto, entre 2.000 y 2.500 rpm en motores de gasolina, y entre 1.500 y 2.000 rpm en diésel. Esto reduce significativamente el consumo de combustible.\n\n- Opciones incorrectas: cambiar por encima de 3.500 rpm supone un gasto innecesario de combustible; ignorar el régimen de revoluciones impide optimizar el consumo\n- Conexión: la conducción eficiente puede suponer un ahorro de combustible de hasta un 15-20% y reduce tanto la contaminación como el desgaste del vehículo\n- Dato clave: gasolina = 2.000-2.500 rpm; diésel = 1.500-2.000 rpm",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_11",
    "tema": "Accidentes, Emergencias y Medio Ambiente",
    "pista": "Circular en la marcha más larga posible a bajas revoluciones consume menos combustible.",
    "tipoPregunta": "directa"
  },
  {
    "id": "pregunta_B028",
    "number": 0,
    "enunciado": "El aceite usado del vehículo debe eliminarse...",
    "opciones": [
      {
        "key": "A",
        "texto": "llevándolo a un punto limpio o taller autorizado"
      },
      {
        "key": "B",
        "texto": "vertiéndolo en cualquier contenedor de reciclaje"
      },
      {
        "key": "C",
        "texto": "enterrándolo en el jardín, ya que es biodegradable"
      }
    ],
    "correcta": "A",
    "explicacion": "El aceite usado es un residuo peligroso que debe llevarse a un punto limpio o a un taller autorizado para su correcta eliminación. Verterlo al suelo, alcantarillas o contenedores normales está prohibido y es una infracción grave.\n\n- Opciones incorrectas: el aceite usado no puede ir a un contenedor de reciclaje normal porque es un residuo peligroso; el aceite de motor no es biodegradable y contamina gravemente el suelo y las aguas subterráneas\n- Conexión: las baterías, los neumáticos usados y el líquido de frenos también son residuos peligrosos que deben entregarse en puntos limpios\n- Error común: pensar que pequeñas cantidades de aceite no causan daño cuando un solo litro puede contaminar hasta un millón de litros de agua",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_11",
    "tema": "Accidentes, Emergencias y Medio Ambiente",
    "pista": "Los residuos del vehículo requieren un tratamiento especial por su toxicidad.",
    "tipoPregunta": "completar"
  },
  {
    "id": "pregunta_B017",
    "number": 0,
    "enunciado": "Un agente le inmoviliza el vehículo porque no tiene seguro obligatorio en vigor. ¿Cuándo se levantará la inmovilización?",
    "opciones": [
      {
        "key": "A",
        "texto": "Cuando presente un seguro válido en vigor"
      },
      {
        "key": "B",
        "texto": "Nunca; un vehículo inmovilizado pasa automáticamente al desguace"
      },
      {
        "key": "C",
        "texto": "Solamente cuando un juez lo autorice expresamente"
      }
    ],
    "correcta": "A",
    "explicacion": "La inmovilización del vehículo se levanta cuando cesa la causa que la motivó. En el caso de falta de seguro, se levanta al presentar un seguro válido en vigor ante los agentes.\n\n- Opciones incorrectas: la inmovilización no implica la destrucción del vehículo, sino su paralización temporal; no se requiere autorización judicial para levantar la inmovilización, basta con subsanar la causa\n- Conexión: si el conductor no puede subsanar la causa de la inmovilización, el vehículo se retira al depósito municipal con los costes de grúa y depósito a cargo del titular\n- Excepción: si el vehículo queda abandonado en depósito durante un período prolongado, puede ser dado de baja definitiva",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_12",
    "tema": "Infracciones y Sanciones",
    "pista": "La inmovilización es una medida temporal que depende de una condición concreta.",
    "tipoPregunta": "situacional"
  },
  {
    "id": "pregunta_B029",
    "number": 0,
    "enunciado": "Recibe una multa de tráfico por una infracción grave. Si la paga en los primeros 20 días, ¿qué beneficio obtiene?",
    "opciones": [
      {
        "key": "A",
        "texto": "Un descuento del 50% en el importe de la multa, aunque renuncia a presentar alegaciones"
      },
      {
        "key": "B",
        "texto": "Un descuento del 50% tanto en la multa como en la pérdida de puntos"
      },
      {
        "key": "C",
        "texto": "Ningún beneficio; las multas de tráfico no tienen descuento por pronto pago"
      }
    ],
    "correcta": "A",
    "explicacion": "El pago de la multa dentro de los 20 días naturales desde la notificación supone un descuento del 50% en el importe económico. Sin embargo, la pérdida de puntos se aplica igualmente y se renuncia al derecho de presentar alegaciones.\n\n- Opciones incorrectas: el descuento solo afecta a la multa económica, nunca a los puntos; el sistema de pronto pago sí existe y es ampliamente utilizado\n- Conexión: si se decide presentar alegaciones, se pierde el derecho al descuento del 50% y se debe pagar el importe completo si la sanción se confirma\n- Error común: creer que el descuento también reduce la pérdida de puntos, cuando estos se detraen en todo caso",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_12",
    "tema": "Infracciones y Sanciones",
    "pista": "El descuento por pronto pago no afecta a todas las consecuencias de la infracción.",
    "tipoPregunta": "directa"
  },
  {
    "id": "pregunta_B030",
    "number": 0,
    "enunciado": "Presta su vehículo a un amigo y este comete una infracción captada por un radar. Usted recibe la denuncia como titular. ¿Qué debe hacer?",
    "opciones": [
      {
        "key": "A",
        "texto": "Identificar al conductor que cometió la infracción en un plazo de 20 días naturales"
      },
      {
        "key": "B",
        "texto": "No hacer nada, ya que la multa siempre recae sobre el titular del vehículo"
      },
      {
        "key": "C",
        "texto": "Pagar la multa y asumir la pérdida de puntos en su permiso"
      }
    ],
    "correcta": "A",
    "explicacion": "Como titular del vehículo, tiene la obligación de identificar al conductor que cometió la infracción en un plazo de 20 días naturales. Si no lo hace, será responsable de la sanción económica, aunque no de la pérdida de puntos.\n\n- Opciones incorrectas: no hacer nada puede conllevar una sanción adicional por no identificar al conductor, que se considera infracción muy grave con multa de hasta 1.500 euros; la pérdida de puntos corresponde al conductor infractor, no al titular\n- Conexión: la responsabilidad del titular se limita a lo económico; los puntos solo se detraen al conductor que cometió la infracción\n- Error común: creer que como titular debe asumir los puntos, cuando la ley distingue entre responsabilidad del titular y del conductor",
    "hasImage": true,
    "imageSrc": null,
    "temaId": "tema_12",
    "tema": "Infracciones y Sanciones",
    "pista": "La ley diferencia entre el propietario del vehículo y quien lo conduce en el momento de la infracción.",
    "tipoPregunta": "situacional"
  }
];
